[2019-01-25T13:38:27.253] [ERROR] dateFileLog - { Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'describe,PGEMaker,orderFrom,MHETypeID,applyDate,limitDate,maker,auditor,makeDate' at line 1
    at Query.Sequence._packetToError (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\work\TOOLSWEB\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    --------------------
    at Protocol._enqueue (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\work\TOOLSWEB\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:474:24)
    at success (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:465:9)
    at Object.exports.safeSuccess (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjError.js:96:13)
    at Object.exports.handleResult (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjError.js:150:12)
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:89:11
    at Ping.onPing (D:\work\TOOLSWEB\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:301:14)
    at Ping.runBound [as _callback] (domain.js:314:12)
  code: 'ER_PARSE_ERROR',
  errno: 1064,
  sqlState: '42000',
  index: 0,
  sql: 'insert into `pm_bills_plan` (BPID,CTRID,topic,describe,PGEMaker,orderFrom,MHETypeID,applyDate,limitDate,maker,auditor,makeDate,auditDate,orderState) values (\'20190125DG108\',\'3\',\'放松放松地方\',\'政府在啥地方\n:cfssdfzfds\n2123123\n\',\'97\',\'邮件\',\'1\',\'2019-01-25\',\'2019-01-28\',\'熊奇龙\',\'\',\'2019-01-25\',\'\',\'0\')' }
[2019-01-25T13:38:27.261] [ERROR] dateFileLog - Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'describe,PGEMaker,orderFrom,MHETypeID,applyDate,limitDate,maker,auditor,makeDate' at line 1
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:990:12)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
[2019-01-25T13:44:02.639] [ERROR] dateFileLog - { Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'describe,PGEMaker,orderFrom,MHETypeID,applyDate,limitDate,maker,auditor,makeDate' at line 1
    at Query.Sequence._packetToError (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\work\TOOLSWEB\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    --------------------
    at Protocol._enqueue (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\work\TOOLSWEB\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:474:24)
    at success (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:465:9)
    at Object.exports.safeSuccess (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjError.js:96:13)
    at Object.exports.handleResult (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjError.js:150:12)
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:89:11
    at Ping.onPing (D:\work\TOOLSWEB\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:301:14)
    at Ping.runBound [as _callback] (domain.js:314:12)
  code: 'ER_PARSE_ERROR',
  errno: 1064,
  sqlState: '42000',
  index: 0,
  sql: 'insert into `pm_bills_plan` (BPID,CTRID,topic,describe,PGEMaker,orderFrom,MHETypeID,applyDate,limitDate,maker,auditor,makeDate,auditDate,orderState) values (\'20190125DG362\',\'大众保泰全程陈建福晟昱锋常兴长兴加财丰得钢得鑫盈成义展亿耐宜婷富国富薪富昱山双鑫建泰鑫兴鸿泰佳洋琮伟郭坤福台湾珑昌连发陇亨龙帅丽伟联有金世纪南映日盛评顺霖城陈明华台湾盈成新高三和/嘉毓舜展翔工通达造记今机统益永睦威欣翔富先特韩先生泳诚龙峰翌评永钛恒威艾必模海强天鼎宁波海马艾尔法弘兴海航艾德森嘉兴昌杭州爱科上海华龙海明伊朗吹瓶机厂商ALVAND海普景全新客户ARRAS海雄海腾金鹰深圳奥翔杭州中亚海州张家港百塑张家港贝司德义乌恒创临沂鸿达博洛克华方温州剑虹保利海江海科宁海华力广东步明（正茂）博纳伯恩博创广东必胜达宁波博荣宁波博信舟山博祥杭州霸洲印度ELECTRONICA昌盛达震宁宁波创美驰鑫创汇张家港诚信常州长江KOREA佳明海荣华大宁波中泰北京中威宏星江门厌优宏振德玛克德塔森特迪科大地德立天东方压铸机东华余姚大爱德库玛德利克汉迈德群宁波森煌杭州大铁西班牙台意德中山华赞亿塑柳州英德宁波恩格恩瑞德舟山精科亿利达华美迪上海塑料佛山技拓建元东莞永佳亿利宏创嘉德镇海福达福尔特晋江奋进法克海浪余姚今鸣富强鑫山西汾机丰铁柳州精业聚隆欣香港金港格林斯顿北仑广德佛山凯迪威格瑞德联升上海光塑东莞广庆无锡格兰宁波格士力震天上海纪威山东统亚韩国现代海波海德海达海德保宁波赫仕余姚海晶香港恒生华联杭州海诚鸿乔山西华丽华美达宁波海鹰巴西HIMACO海光华磊复力海日海宁华塑海天宁波恒达宏荣海太海星福州海燕宁波海润慧创香港怡光台进利鑫华章月清海田黄元运坚达广东俊华上海金纬江达金天机今顺黄岩巨光韩国进和张家港玖威捷劲扬州吉达杭州捷立奇明宁波嘉塑USACOASTAL佳拿达今通金矶嘉信杰腾广州佳速香港劲宇嘉伟捷泰纪元奉化嘉正康力科隆阁广东库特科腾柳州开宇科鲁迪康润科朗斯东莞科骏普利鑫台州科力科罗斯克虏伯科仕特宁波可司曼凯威海涌明大联鑫力维张家港绿环晋江力达朗亿柳州力风利广龙汇汇利杭州联塑力劲无锡蓝力力创雷盟南一苏州立注力泉力速柳州塑料瑞安力泰成路双马广州利文立信香港利源江北利源铭威铭辉满誉宁波明大迈道巨能美格明和铭捷MILANKALA迈朗明润江南模塑伊朗客户MecaTronic明广伟业迈讯弘粤广东南钢宁波塑料诺恩余姚朗格恩港恒生耐乐宁波宁塑澳洲NEWTECH奥德温州瓯江宁波欧意莱百冠杭州欧亚派瑞特盘石宝捷艾力士PARSIAN鹏泰香港宝源潘珠红东莞侨恩柳州奇峰骐合中山全立发千普奇盛常州乾易利瑞宝芜湖润东REGLER\n日进锐能容声(华联)香港隆源湖北福星温州圣邦思必拓泓利双鹰SFCE宁波三友声凯索迪龙芜湖三顺广州华新科舜力-郭力生山东胜岳常州赛恩双科杭州胜源宁波晟菲杭州珊而立宁波三顺双盛/圣特龙胜沃顺兴合磨机三元神舟(张家港）香港达明勤川华南天成宁波总厂香港科技特佳天津塑料无锡天惠山东通佳宁波今机杭州腾骏弘讯天达宁波海通天沅彤熹泰瑞临安台塑北京泰坦通用同发东莞台旺同鑫大禹太原天章甬江怡泰利香港永胜宁波威力仕王海民伟达华达维达万高无锡华鸿维联伟祺华雄威腾(注吹机）威洋夏天希格玛湘通杭州新登张家港鑫锐恒北京信冠新海太佛山祥源协力昆山欣斯特雄泰宁波雄信永安伊之密东莞盈成永旺鹏岳余姚华城亚泰仁兴优灿甬江业勤亚力士张家港意玖优诺姆香港友和余姚塑料甬丰鹰图银山舟山永泰余姚华泰永生耀威优铸广东赞扬东莞中泰震海誉舟山震宇中扬震飞扬州中环振华中汇珠海震捷山东重汽张家港自强金鹰伊朗代理Zohrab温州至上申达震甬\',\'阿三的发生地方\',\'在啥地方阿斯蒂芬阿斯蒂芬 \',\'曹峥蒋伟贞孙凌财李源朱宝安劳亚丹杨勇李斌张亮许静静王光漫周玲燕唐奕磊刘梦钟静伟梅迪凡张胜勇王涛陈立毅王莉周永汉陈波王浩宇傅霞银张磊沈航凯虞晔文俞洋裘凯迪王锋张凯陈浩天施宇城林盛谢丽君熊奇龙张铖单霖霖孙维泽方林杰贾志成柳张成谷永亮周颖赵韦杨金鑫\',\' \n                     邮件\n                     电话\n                     传真\n                     微信\n                     其他\n                     \',\'普通机双色机立式机合模机橡胶机注吹机压铸机新机型\',\'2019-01-25\',\'2019-01-28\',\'\',\'曹峥蒋伟贞孙凌财李源朱宝安劳亚丹杨勇李斌张亮许静静王光漫周玲燕唐奕磊刘梦钟静伟梅迪凡张胜勇王涛陈立毅王莉周永汉陈波王浩宇傅霞银张磊沈航凯虞晔文俞洋裘凯迪王锋张凯陈浩天施宇城林盛谢丽君熊奇龙张铖单霖霖孙维泽方林杰贾志成柳张成谷永亮周颖赵韦杨金鑫\',\'2019-01-25\',\'2019-01-25\',\'1\')' }
[2019-01-25T13:44:02.644] [ERROR] dateFileLog - Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'describe,PGEMaker,orderFrom,MHETypeID,applyDate,limitDate,maker,auditor,makeDate' at line 1
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:990:12)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
[2019-01-25T13:46:45.679] [ERROR] dateFileLog - { Error: ER_TRUNCATED_WRONG_VALUE: Incorrect date value: '' for column 'auditDate' at row 1
    at Query.Sequence._packetToError (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\work\TOOLSWEB\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    --------------------
    at Protocol._enqueue (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\work\TOOLSWEB\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:474:24)
    at success (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:465:9)
    at Object.exports.safeSuccess (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjError.js:96:13)
    at Object.exports.handleResult (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjError.js:150:12)
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:89:11
    at Ping.onPing (D:\work\TOOLSWEB\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:301:14)
    at Ping.runBound [as _callback] (domain.js:314:12)
  code: 'ER_TRUNCATED_WRONG_VALUE',
  errno: 1292,
  sqlState: '22007',
  index: 0,
  sql: 'insert into `pm_bills_plan` (BPID,CTRID,topic,PGEMaker,orderFrom,MHETypeID,applyDate,limitDate,maker,auditor,makeDate,auditDate,orderState) values (\'20190125DG733\',\'晟昱锋\',\'洒洒的发生的\',\'张亮\',\'邮件\',\'橡胶机\',\'2019-01-25\',\'2019-01-28\',\'\',\'\',\'2019-01-25\',\'\',\'0\')' }
[2019-01-25T13:46:45.690] [ERROR] dateFileLog - Error: ER_TRUNCATED_WRONG_VALUE: Incorrect date value: '' for column 'auditDate' at row 1
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:990:12)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
[2019-01-25T14:05:52.026] [ERROR] dateFileLog - { Error: ER_TRUNCATED_WRONG_VALUE: Incorrect date value: '' for column 'auditDate' at row 1
    at Query.Sequence._packetToError (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\work\TOOLSWEB\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    --------------------
    at Protocol._enqueue (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\work\TOOLSWEB\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:474:24)
    at success (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:465:9)
    at Object.exports.safeSuccess (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjError.js:96:13)
    at Object.exports.handleResult (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjError.js:150:12)
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:89:11
    at Ping.onPing (D:\work\TOOLSWEB\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:301:14)
    at Ping.runBound [as _callback] (domain.js:314:12)
  code: 'ER_TRUNCATED_WRONG_VALUE',
  errno: 1292,
  sqlState: '22007',
  index: 0,
  sql: 'insert into `pm_bills_plan` (BPID,CTRID,topic,PGEMaker,orderFrom,MHETypeID,applyDate,limitDate,maker,auditor,makeDate,auditDate,orderState) values (\'20190125DG511\',\'\',\'\',\'\',\'邮件\',\'\',\'2019-01-25\',\'2019-01-28\',\'\',\'\',\'2019-01-25\',\'\',\'0\')' }
[2019-01-25T14:05:52.030] [ERROR] dateFileLog - Error: ER_TRUNCATED_WRONG_VALUE: Incorrect date value: '' for column 'auditDate' at row 1
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:990:12)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
[2019-01-25T14:21:49.723] [ERROR] dateFileLog - { Error: ER_TRUNCATED_WRONG_VALUE: Incorrect date value: '' for column 'auditDate' at row 1
    at Query.Sequence._packetToError (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\work\TOOLSWEB\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    --------------------
    at Protocol._enqueue (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\work\TOOLSWEB\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:474:24)
    at success (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:465:9)
    at Object.exports.safeSuccess (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjError.js:96:13)
    at Object.exports.handleResult (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjError.js:150:12)
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:89:11
    at Ping.onPing (D:\work\TOOLSWEB\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:301:14)
    at Ping.runBound [as _callback] (domain.js:314:12)
  code: 'ER_TRUNCATED_WRONG_VALUE',
  errno: 1292,
  sqlState: '22007',
  index: 0,
  sql: 'insert into `pm_bills_plan` (BPID,CTRID,topic,PGEMaker,orderFrom,MHETypeID,applyDate,limitDate,maker,auditor,makeDate,auditDate,orderState) values (\'20190125DG110\',\'\',\'\',\'\',\'邮件\',\'\',\'2019-01-25\',\'2019-01-28\',\'\',\'\',\'2019-01-25\',\'\',\'0\')' }
[2019-01-25T14:21:49.725] [ERROR] dateFileLog - Error: ER_TRUNCATED_WRONG_VALUE: Incorrect date value: '' for column 'auditDate' at row 1
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:990:12)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
[2019-01-25T14:22:22.959] [ERROR] dateFileLog - { Error: ER_TRUNCATED_WRONG_VALUE: Incorrect date value: '' for column 'auditDate' at row 1
    at Query.Sequence._packetToError (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\work\TOOLSWEB\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    --------------------
    at Protocol._enqueue (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\work\TOOLSWEB\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:474:24)
    at success (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:465:9)
    at Object.exports.safeSuccess (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjError.js:96:13)
    at Object.exports.handleResult (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjError.js:150:12)
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:89:11
    at Ping.onPing (D:\work\TOOLSWEB\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:301:14)
    at Ping.runBound [as _callback] (domain.js:314:12)
  code: 'ER_TRUNCATED_WRONG_VALUE',
  errno: 1292,
  sqlState: '22007',
  index: 0,
  sql: 'insert into `pm_bills_plan` (BPID,CTRID,topic,PGEMaker,orderFrom,MHETypeID,applyDate,limitDate,maker,auditor,makeDate,auditDate,orderState) values (\'20190125DG995\',\'\',\'\',\'\',\'邮件\',\'\',\'2019-01-25\',\'2019-01-28\',\'\',\'\',\'2019-01-25\',\'\',\'0\')' }
[2019-01-25T14:22:22.969] [ERROR] dateFileLog - Error: ER_TRUNCATED_WRONG_VALUE: Incorrect date value: '' for column 'auditDate' at row 1
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:990:12)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
[2019-01-25T14:23:11.327] [ERROR] dateFileLog - { Error: ER_TRUNCATED_WRONG_VALUE: Incorrect date value: '' for column 'auditDate' at row 1
    at Query.Sequence._packetToError (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\work\TOOLSWEB\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    --------------------
    at Protocol._enqueue (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\work\TOOLSWEB\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:474:24)
    at success (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:465:9)
    at Object.exports.safeSuccess (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjError.js:96:13)
    at Object.exports.handleResult (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjError.js:150:12)
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:89:11
    at Ping.onPing (D:\work\TOOLSWEB\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:301:14)
    at Ping.runBound [as _callback] (domain.js:314:12)
  code: 'ER_TRUNCATED_WRONG_VALUE',
  errno: 1292,
  sqlState: '22007',
  index: 0,
  sql: 'insert into `pm_bills_plan` (BPID,CTRID,topic,PGEMaker,orderFrom,MHETypeID,applyDate,limitDate,maker,auditor,makeDate,auditDate,orderState) values (\'20190125DG995\',\'\',\'\',\'\',\'邮件\',\'\',\'2019-01-25\',\'2019-01-28\',\'\',\'\',\'2019-01-25\',\'\',\'0\')' }
[2019-01-25T14:23:11.331] [ERROR] dateFileLog - Error: ER_TRUNCATED_WRONG_VALUE: Incorrect date value: '' for column 'auditDate' at row 1
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:990:12)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
[2019-01-25T14:29:24.544] [ERROR] dateFileLog - { Error: ER_TRUNCATED_WRONG_VALUE: Incorrect date value: '' for column 'auditDate' at row 1
    at Query.Sequence._packetToError (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\work\TOOLSWEB\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    --------------------
    at Protocol._enqueue (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\work\TOOLSWEB\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:474:24)
    at success (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:465:9)
    at Object.exports.safeSuccess (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjError.js:96:13)
    at Object.exports.handleResult (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjError.js:150:12)
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:89:11
    at Ping.onPing (D:\work\TOOLSWEB\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:301:14)
    at Ping.runBound [as _callback] (domain.js:314:12)
  code: 'ER_TRUNCATED_WRONG_VALUE',
  errno: 1292,
  sqlState: '22007',
  index: 0,
  sql: 'insert into `pm_bills_plan` (BPID,CTRID,topic,PGEMaker,orderFrom,MHETypeID,applyDate,limitDate,maker,auditor,makeDate,auditDate,orderState) values (\'20190125DG249\',\'\',\'\',\'\',\'邮件\',\'\',\'2019-01-25\',\'2019-01-28\',\'\',\'\',\'2019-01-25\',\'\',\'0\')' }
[2019-01-25T14:29:24.551] [ERROR] dateFileLog - Error: ER_TRUNCATED_WRONG_VALUE: Incorrect date value: '' for column 'auditDate' at row 1
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:990:12)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
[2019-01-25T14:45:29.547] [ERROR] dateFileLog - { Error: ER_TRUNCATED_WRONG_VALUE: Incorrect date value: 'null' for column 'auditDate' at row 1
    at Query.Sequence._packetToError (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\work\TOOLSWEB\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    --------------------
    at Protocol._enqueue (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\work\TOOLSWEB\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:474:24)
    at success (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:465:9)
    at Object.exports.safeSuccess (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjError.js:96:13)
    at Object.exports.handleResult (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjError.js:150:12)
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:89:11
    at Ping.onPing (D:\work\TOOLSWEB\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:301:14)
    at Ping.runBound [as _callback] (domain.js:314:12)
  code: 'ER_TRUNCATED_WRONG_VALUE',
  errno: 1292,
  sqlState: '22007',
  index: 0,
  sql: 'insert into `pm_bills_plan` (BPID,CTRID,topic,PGEMaker,orderFrom,MHETypeID,applyDate,limitDate,maker,auditor,makeDate,auditDate,orderState) values (\'20190125DG531\',\'null\',\'null\',\'null\',\'邮件\',\'null\',\'2019-01-25\',\'2019-01-28\',\'null\',\'null\',\'2019-01-25\',\'null\',\'0\')' }
[2019-01-25T14:45:29.551] [ERROR] dateFileLog - Error: ER_TRUNCATED_WRONG_VALUE: Incorrect date value: 'null' for column 'auditDate' at row 1
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:990:12)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
[2019-01-25T14:49:02.240] [ERROR] dateFileLog - { Error: ER_BAD_NULL_ERROR: Column 'CTRID' cannot be null
    at Query.Sequence._packetToError (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\work\TOOLSWEB\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    --------------------
    at Protocol._enqueue (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\work\TOOLSWEB\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:474:24)
    at success (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:465:9)
    at Object.exports.safeSuccess (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjError.js:96:13)
    at Object.exports.handleResult (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjError.js:150:12)
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:89:11
    at Ping.onPing (D:\work\TOOLSWEB\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:301:14)
    at Ping.runBound [as _callback] (domain.js:314:12)
  code: 'ER_BAD_NULL_ERROR',
  errno: 1048,
  sqlState: '23000',
  index: 0,
  sql: 'insert into `pm_bills_plan` (BPID,CTRID,topic,PGEMaker,orderFrom,MHETypeID,applyDate,limitDate,maker,auditor,makeDate,auditDate,orderState) values (\'20190125DG906\',null,null,null,\'邮件\',null,\'2019-01-25\',\'2019-01-28\',null,null,\'2019-01-25\',null,\'0\')' }
[2019-01-25T14:49:02.245] [ERROR] dateFileLog - Error: ER_BAD_NULL_ERROR: Column 'CTRID' cannot be null
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:990:12)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
[2019-01-25T14:53:43.578] [ERROR] dateFileLog - { Error: ER_BAD_NULL_ERROR: Column 'CTRID' cannot be null
    at Query.Sequence._packetToError (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\work\TOOLSWEB\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    --------------------
    at Protocol._enqueue (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\work\TOOLSWEB\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:474:24)
    at success (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:465:9)
    at Object.exports.safeSuccess (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjError.js:96:13)
    at Object.exports.handleResult (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjError.js:150:12)
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:89:11
    at Ping.onPing (D:\work\TOOLSWEB\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:301:14)
    at Ping.runBound [as _callback] (domain.js:314:12)
  code: 'ER_BAD_NULL_ERROR',
  errno: 1048,
  sqlState: '23000',
  index: 0,
  sql: 'insert into `pm_bills_plan` (BPID,CTRID,topic,PGEMaker,orderFrom,MHETypeID,applyDate,limitDate,maker,auditor,makeDate,auditDate,orderState) values (\'20190125DG641\',null,null,null,\'邮件\',null,\'2019-01-25\',\'2019-01-28\',null,null,\'2019-01-25\',\'2019-01-25\',\'1\')' }
[2019-01-25T14:53:43.582] [ERROR] dateFileLog - Error: ER_BAD_NULL_ERROR: Column 'CTRID' cannot be null
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:990:12)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
