[2018-09-20T13:40:39.996] [ERROR] dateFileLog - Error: Password is not correct for userAID Admin.
    at callback_getUser (D:\work\Source\yujiang.Foil.Node.BizServer\biz\account\checkLogin.js:178:24)
    at D:\work\Source\yujiang.Foil.Node\src\yjError.js:129:4
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.safeCallback (D:\work\Source\yujiang.Foil.Node\src\yjError.js:128:11)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:142:11)
    at Query.<anonymous> (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:480:33)
    at bound (domain.js:396:14)
    at Query.runBound [as _callback] (domain.js:409:12)
    at Query.Sequence.end (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
    at Query._handleFinalResultPacket (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Query.js:143:8)
[2018-09-20T13:40:40.002] [ERROR] dateFileLog - Error: Password is not correct for userAID Admin.
    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:37:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at IncomingMessage.emit (events.js:187:15)
    at IncomingMessage.EventEmitter.emit (domain.js:460:23)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[2018-09-20T13:40:42.914] [ERROR] dateFileLog - Error: Password is not correct for userAID Admin.
    at callback_getUser (D:\work\Source\yujiang.Foil.Node.BizServer\biz\account\checkLogin.js:178:24)
    at D:\work\Source\yujiang.Foil.Node\src\yjError.js:129:4
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.safeCallback (D:\work\Source\yujiang.Foil.Node\src\yjError.js:128:11)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:142:11)
    at Query.<anonymous> (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:480:33)
    at bound (domain.js:396:14)
    at Query.runBound [as _callback] (domain.js:409:12)
    at Query.Sequence.end (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
    at Query._handleFinalResultPacket (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Query.js:143:8)
[2018-09-20T13:40:42.916] [ERROR] dateFileLog - Error: Password is not correct for userAID Admin.
    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:37:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at IncomingMessage.emit (events.js:187:15)
    at IncomingMessage.EventEmitter.emit (domain.js:460:23)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[2018-09-20T13:40:48.316] [ERROR] dateFileLog - Error: Password is not correct for userAID Admin.
    at callback_getUser (D:\work\Source\yujiang.Foil.Node.BizServer\biz\account\checkLogin.js:178:24)
    at D:\work\Source\yujiang.Foil.Node\src\yjError.js:129:4
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.safeCallback (D:\work\Source\yujiang.Foil.Node\src\yjError.js:128:11)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:142:11)
    at Query.<anonymous> (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:480:33)
    at bound (domain.js:396:14)
    at Query.runBound [as _callback] (domain.js:409:12)
    at Query.Sequence.end (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
    at Query._handleFinalResultPacket (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Query.js:143:8)
[2018-09-20T13:40:48.319] [ERROR] dateFileLog - Error: Password is not correct for userAID Admin.
    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:37:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at IncomingMessage.emit (events.js:187:15)
    at IncomingMessage.EventEmitter.emit (domain.js:460:23)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[2018-09-20T13:40:51.991] [ERROR] dateFileLog - Error: Password is not correct for userAID Admin.
    at callback_getUser (D:\work\Source\yujiang.Foil.Node.BizServer\biz\account\checkLogin.js:178:24)
    at D:\work\Source\yujiang.Foil.Node\src\yjError.js:129:4
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.safeCallback (D:\work\Source\yujiang.Foil.Node\src\yjError.js:128:11)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:142:11)
    at Query.<anonymous> (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:480:33)
    at bound (domain.js:396:14)
    at Query.runBound [as _callback] (domain.js:409:12)
    at Query.Sequence.end (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
    at Query._handleFinalResultPacket (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Query.js:143:8)
[2018-09-20T13:40:51.992] [ERROR] dateFileLog - Error: Password is not correct for userAID Admin.
    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:37:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at IncomingMessage.emit (events.js:187:15)
    at IncomingMessage.EventEmitter.emit (domain.js:460:23)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[2018-09-20T13:47:49.264] [ERROR] dateFileLog - { Error: Failed to lookup view "D:\work\Source\toolsWeb\web\app\bear\BearSub.{v}.ejs" in views directory "/"
    at Function.render (D:\work\Source\node_modules\express\lib\application.js:579:17)
    at ServerResponse.render (D:\work\Source\node_modules\express\lib\response.js:961:7)
    at doIt (D:\work\Source\yujiang.Foil.Node\src\yjMVC.js:85:7)
    at Object.success (D:\work\Source\yujiang.Foil.Node\src\yjMVC.js:42:5)
    at Object.getUserProcessAuthority (D:\work\Source\yujiang.Foil.Node.BizServer\biz\org\processAuthority.js:727:12)
    at Object.getUserProcessAuthority (D:\work\Source\yujiang.Foil.Node\src\yjAuthority.js:58:22)
    at render (D:\work\Source\yujiang.Foil.Node\src\yjMVC.js:38:15)
    at proc_success (D:\work\Source\yujiang.Foil.Node\src\yjMVC.js:111:3)
    at buildData (D:\work\Source\yujiang.Foil.Node\src\yjMVC.js:198:4)
    at D:\work\Source\yujiang.Foil.Node\src\yjMVC.js:129:5
  view:
   View {
     defaultEngine: 'ejs',
     ext: '.ejs',
     name: 'D:\\work\\Source\\toolsWeb\\web\\app\\bear\\BearSub.{v}.ejs',
     root: '/',
     engine: [Function],
     path: undefined } }
