[2018-11-08T13:59:31.497] [ERROR] dateFileLog - { Error: ER_DATA_TOO_LONG: Data too long for column 'staff_Sex' at row 1
    at Query.Sequence._packetToError (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\work\Source\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\work\Source\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    --------------------
    at Protocol._enqueue (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\work\Source\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:474:24)
    at success (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:465:9)
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:148:12)
    at D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:89:11
    at Ping.onPing (D:\work\Source\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:301:14)
    at Ping.runBound [as _callback] (domain.js:314:12)
  code: 'ER_DATA_TOO_LONG',
  errno: 1406,
  sqlState: '22001',
  index: 0,
  sql: 'insert into PM_staffs (staff_ID,staff_Name,staff_Sex,staff_User) values (\'1111\',\'1111\',\'111\',\'\')' }
[2018-11-08T13:59:31.505] [ERROR] dateFileLog - Error: ER_DATA_TOO_LONG: Data too long for column 'staff_Sex' at row 1
    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
[2018-11-08T13:59:49.602] [ERROR] dateFileLog - { Error: ER_DATA_TOO_LONG: Data too long for column 'staff_Sex' at row 1
    at Query.Sequence._packetToError (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\work\Source\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\work\Source\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    --------------------
    at Protocol._enqueue (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\work\Source\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:474:24)
    at success (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:465:9)
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:148:12)
    at D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:89:11
    at Ping.onPing (D:\work\Source\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:301:14)
    at Ping.runBound [as _callback] (domain.js:314:12)
  code: 'ER_DATA_TOO_LONG',
  errno: 1406,
  sqlState: '22001',
  index: 0,
  sql: 'insert into PM_staffs (staff_ID,staff_Name,staff_Sex,staff_User) values (\'111\',\'1111\',\'111\',\'\')' }
[2018-11-08T13:59:49.605] [ERROR] dateFileLog - Error: ER_DATA_TOO_LONG: Data too long for column 'staff_Sex' at row 1
    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
[2018-11-08T16:35:20.791] [ERROR] dateFileLog - { Error: ER_DUP_ENTRY: Duplicate entry 'staffs' for key 'UNIQUE'
    at Query.Sequence._packetToError (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\work\Source\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\work\Source\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    --------------------
    at Protocol._enqueue (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\work\Source\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:474:24)
    at success (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:465:9)
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:148:12)
    at D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:89:11
    at Ping.onPing (D:\work\Source\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:301:14)
    at Ping.runBound [as _callback] (domain.js:314:12)
  code: 'ER_DUP_ENTRY',
  errno: 1062,
  sqlState: '23000',
  index: 0,
  sql: ' insert into `Processes`( `ProcessAID`,`Name`,`ExecName`,`ImageAID`,`Description`,`Hidden`,`SortNumber`,`ProcessOIDParent`) values(?,?,?,?,?,?,?,?)' }
[2018-11-08T16:35:20.795] [ERROR] dateFileLog - Error: ER_DUP_ENTRY: Duplicate entry 'staffs' for key 'UNIQUE'
    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
[2018-11-08T16:42:21.582] [ERROR] dateFileLog - { Error: ER_NO_SUCH_TABLE: Table 'toolsweb.oa_staffs' doesn't exist
    at Query.Sequence._packetToError (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\work\Source\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\work\Source\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    --------------------
    at Protocol._enqueue (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\work\Source\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:474:24)
    at success (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:465:9)
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:148:12)
    at D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:89:11
    at Ping.onPing (D:\work\Source\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:301:14)
    at Ping.runBound [as _callback] (domain.js:314:12)
  code: 'ER_NO_SUCH_TABLE',
  errno: 1146,
  sqlState: '42S02',
  index: 0,
  sql: 'SELECT * FROM OA_staffs' }
[2018-11-08T16:42:21.585] [ERROR] dateFileLog - Error: ER_NO_SUCH_TABLE: Table 'toolsweb.oa_staffs' doesn't exist
    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
[2018-11-08T16:42:54.384] [ERROR] dateFileLog - { Error: ER_NO_SUCH_TABLE: Table 'toolsweb.oa_staffs' doesn't exist
    at Query.Sequence._packetToError (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\work\Source\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\work\Source\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    --------------------
    at Protocol._enqueue (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\work\Source\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:474:24)
    at success (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:465:9)
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:148:12)
    at D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:89:11
    at Ping.onPing (D:\work\Source\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:301:14)
    at Ping.runBound [as _callback] (domain.js:314:12)
  code: 'ER_NO_SUCH_TABLE',
  errno: 1146,
  sqlState: '42S02',
  index: 0,
  sql: 'SELECT * FROM OA_staffs' }
[2018-11-08T16:42:54.385] [ERROR] dateFileLog - Error: ER_NO_SUCH_TABLE: Table 'toolsweb.oa_staffs' doesn't exist
    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
