[2018-09-14 13:42:20.089] [ERROR] dateFileLog - { Error: ENOENT: no such file or directory, scandir 'D:\work\Source\toolsWeb\webServer\system\release\data'
    at Error (native)
    at Object.fs.readdirSync (fs.js:952:18)
    at scanOne (D:\work\Source\yujiang.Foil.Node\src\yjDirectory.js:41:19)
    at Object.scanFiles (D:\work\Source\yujiang.Foil.Node\src\yjDirectory.js:68:10)
    at Object.<anonymous> (D:\work\Source\yujiang.Foil.Node.WebServer\app\system\release\readNewestVersion.{autorun}.js:13:26)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
  errno: -4058,
  code: 'ENOENT',
  syscall: 'scandir',
  path: 'D:\\work\\Source\\toolsWeb\\webServer\\system\\release\\data' }
[2018-09-14 13:43:04.828] [ERROR] dateFileLog - { Error: ENOENT: no such file or directory, scandir 'D:\work\Source\toolsWeb\web\system\release\data'
    at Error (native)
    at Object.fs.readdirSync (fs.js:952:18)
    at scanOne (D:\work\Source\yujiang.Foil.Node\src\yjDirectory.js:41:19)
    at Object.scanFiles (D:\work\Source\yujiang.Foil.Node\src\yjDirectory.js:68:10)
    at Object.<anonymous> (D:\work\Source\yujiang.Foil.Node.WebServer\app\system\release\readNewestVersion.{autorun}.js:13:26)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
  errno: -4058,
  code: 'ENOENT',
  syscall: 'scandir',
  path: 'D:\\work\\Source\\toolsWeb\\web\\system\\release\\data' }
[2018-09-14 13:46:53.813] [ERROR] dateFileLog - Error: Password is not correct for userAID Admin.
    at callback_getUser (D:\work\Source\yujiang.Foil.Node.BizServer\biz\account\checkLogin.js:178:24)
    at D:\work\Source\yujiang.Foil.Node\src\yjError.js:129:4
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.safeCallback (D:\work\Source\yujiang.Foil.Node\src\yjError.js:128:11)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:142:11)
    at Query.<anonymous> (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:480:33)
    at bound (domain.js:280:14)
    at Query.runBound [as _callback] (domain.js:293:12)
    at Query.Sequence.end (D:\work\Source\yujiang.NodeFoil.Npm\mysql\lib\protocol\sequences\Sequence.js:88:24)
    at Query._handleFinalResultPacket (D:\work\Source\yujiang.NodeFoil.Npm\mysql\lib\protocol\sequences\Query.js:139:8)
[2018-09-14 13:46:53.832] [ERROR] dateFileLog - Error: Password is not correct for userAID Admin.
    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:37:34
    at Request.callback (D:\work\Source\yujiang.NodeFoil.Npm\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\yujiang.NodeFoil.Npm\superagent\lib\node\index.js:990:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
[2018-09-14 13:47:00.989] [ERROR] dateFileLog - { TypeError: D:\work\Source\yujiang.Foil.Node.WebServer\themes\layout\mes\master.notree.ejs:12
    10| 	}
    11| </script>
 >> 12| <% layout('layout.ejs') -%> 
    13| <% block('top_left',partial("top-left.ejs")) -%> 
    14| <% block('top_right',partial("top-right.ejs")) -%> 
    15| <% block('header', partial("top.ejs")) -%> 

D:\work\Source\yujiang.Foil.Node.WebServer\themes\layout\mes\top-right.ejs:26
    24| <script type="text/javascript">
    25| 
 >> 26|       var userImage = <%-JSON.stringify(locals.config.mesTM.userImg)%>;
    27|       if(userImage){
    28|       	  var user_img=new Image();
    29| 	      user_img.src = userImage;

Cannot read property 'userImg' of undefined
    at eval (eval at <anonymous> (D:\work\Source\yujiang.NodeFoil.Npm\ejs-locals\node_modules\ejs\lib\ejs.js:237:14), <anonymous>:30:1312)
    at eval (eval at <anonymous> (D:\work\Source\yujiang.NodeFoil.Npm\ejs-locals\node_modules\ejs\lib\ejs.js:237:14), <anonymous>:30:3368)
    at D:\work\Source\yujiang.NodeFoil.Npm\ejs-locals\node_modules\ejs\lib\ejs.js:250:15
    at Object.exports.render (D:\work\Source\yujiang.NodeFoil.Npm\ejs-locals\node_modules\ejs\lib\ejs.js:288:13)
    at render (D:\work\Source\yujiang.NodeFoil.Npm\ejs-locals\index.js:334:20)
    at Object.partial (D:\work\Source\yujiang.NodeFoil.Npm\ejs-locals\index.js:376:12)
    at eval (eval at <anonymous> (D:\work\Source\yujiang.NodeFoil.Npm\ejs-locals\node_modules\ejs\lib\ejs.js:237:14), <anonymous>:30:638)
    at eval (eval at <anonymous> (D:\work\Source\yujiang.NodeFoil.Npm\ejs-locals\node_modules\ejs\lib\ejs.js:237:14), <anonymous>:30:857)
    at D:\work\Source\yujiang.NodeFoil.Npm\ejs-locals\node_modules\ejs\lib\ejs.js:250:15
    at Object.exports.render (D:\work\Source\yujiang.NodeFoil.Npm\ejs-locals\node_modules\ejs\lib\ejs.js:288:13)
  path: 'D:\\work\\Source\\yujiang.Foil.Node.WebServer\\themes\\layout\\mes\\master.notree.ejs' }
[2018-09-14 13:54:22.083] [ERROR] dateFileLog - { TypeError: D:\work\Source\yujiang.Foil.Node.WebServer\themes\layout\mes\master.notree.ejs:12
    10| 	}
    11| </script>
 >> 12| <% layout('layout.ejs') -%> 
    13| <% block('top_left',partial("top-left.ejs")) -%> 
    14| <% block('top_right',partial("top-right.ejs")) -%> 
    15| <% block('header', partial("top.ejs")) -%> 

D:\work\Source\yujiang.Foil.Node.WebServer\themes\layout\mes\top-right.ejs:26
    24| <script type="text/javascript">
    25| 
 >> 26|       var userImage = <%-JSON.stringify(locals.config.mesTM.userImg)%>;
    27|       if(userImage){
    28|       	  var user_img=new Image();
    29| 	      user_img.src = userImage;

Cannot read property 'userImg' of undefined
    at eval (eval at <anonymous> (D:\work\Source\yujiang.NodeFoil.Npm\ejs-locals\node_modules\ejs\lib\ejs.js:237:14), <anonymous>:30:1312)
    at eval (eval at <anonymous> (D:\work\Source\yujiang.NodeFoil.Npm\ejs-locals\node_modules\ejs\lib\ejs.js:237:14), <anonymous>:30:3368)
    at D:\work\Source\yujiang.NodeFoil.Npm\ejs-locals\node_modules\ejs\lib\ejs.js:250:15
    at Object.exports.render (D:\work\Source\yujiang.NodeFoil.Npm\ejs-locals\node_modules\ejs\lib\ejs.js:288:13)
    at render (D:\work\Source\yujiang.NodeFoil.Npm\ejs-locals\index.js:334:20)
    at Object.partial (D:\work\Source\yujiang.NodeFoil.Npm\ejs-locals\index.js:376:12)
    at eval (eval at <anonymous> (D:\work\Source\yujiang.NodeFoil.Npm\ejs-locals\node_modules\ejs\lib\ejs.js:237:14), <anonymous>:30:638)
    at eval (eval at <anonymous> (D:\work\Source\yujiang.NodeFoil.Npm\ejs-locals\node_modules\ejs\lib\ejs.js:237:14), <anonymous>:30:857)
    at D:\work\Source\yujiang.NodeFoil.Npm\ejs-locals\node_modules\ejs\lib\ejs.js:250:15
    at Object.exports.render (D:\work\Source\yujiang.NodeFoil.Npm\ejs-locals\node_modules\ejs\lib\ejs.js:288:13)
  path: 'D:\\work\\Source\\yujiang.Foil.Node.WebServer\\themes\\layout\\mes\\master.notree.ejs' }
[2018-09-14 13:54:47.110] [ERROR] dateFileLog - { Error: ENOENT: no such file or directory, open 'D:\work\Source\yujiang.Foil.Node.WebServer\app\processundefined'
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.readFileSync (fs.js:509:33)
    at sender.success (D:\work\Source\yujiang.Foil.Node.WebServer\app\process\getProcessTree.{m}.js:19:20)
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:148:12)
    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:41:14
    at Request.callback (D:\work\Source\yujiang.NodeFoil.Npm\superagent\lib\node\index.js:785:12)
    at Stream.<anonymous> (D:\work\Source\yujiang.NodeFoil.Npm\superagent\lib\node\index.js:990:12)
    at emitNone (events.js:91:20)
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'D:\\work\\Source\\yujiang.Foil.Node.WebServer\\app\\processundefined' }
[2018-09-14 13:55:50.659] [ERROR] dateFileLog - { Error: ENOENT: no such file or directory, open 'D:\work\Source\yujiang.Foil.Node.WebServer\app\processundefined'
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.readFileSync (fs.js:509:33)
    at sender.success (D:\work\Source\yujiang.Foil.Node.WebServer\app\process\getProcessTree.{m}.js:19:20)
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:148:12)
    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:41:14
    at Request.callback (D:\work\Source\yujiang.NodeFoil.Npm\superagent\lib\node\index.js:785:12)
    at Stream.<anonymous> (D:\work\Source\yujiang.NodeFoil.Npm\superagent\lib\node\index.js:990:12)
    at emitNone (events.js:91:20)
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'D:\\work\\Source\\yujiang.Foil.Node.WebServer\\app\\processundefined' }
[2018-09-14 13:56:59.475] [ERROR] dateFileLog - { Error: ENOENT: no such file or directory, open 'D:\work\Source\yujiang.Foil.Node.WebServer\app\processundefined'
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.readFileSync (fs.js:509:33)
    at sender.success (D:\work\Source\yujiang.Foil.Node.WebServer\app\process\getProcessTree.{m}.js:19:20)
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:148:12)
    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:41:14
    at Request.callback (D:\work\Source\yujiang.NodeFoil.Npm\superagent\lib\node\index.js:785:12)
    at Stream.<anonymous> (D:\work\Source\yujiang.NodeFoil.Npm\superagent\lib\node\index.js:990:12)
    at emitNone (events.js:91:20)
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'D:\\work\\Source\\yujiang.Foil.Node.WebServer\\app\\processundefined' }
[2018-09-14 13:58:35.801] [ERROR] dateFileLog - { Error: ENOENT: no such file or directory, open 'D:\work\Source\yujiang.Foil.Node.WebServer\app\processundefined'
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.readFileSync (fs.js:509:33)
    at sender.success (D:\work\Source\yujiang.Foil.Node.WebServer\app\process\getProcessTree.{m}.js:19:20)
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:148:12)
    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:41:14
    at Request.callback (D:\work\Source\yujiang.NodeFoil.Npm\superagent\lib\node\index.js:785:12)
    at Stream.<anonymous> (D:\work\Source\yujiang.NodeFoil.Npm\superagent\lib\node\index.js:990:12)
    at emitNone (events.js:91:20)
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'D:\\work\\Source\\yujiang.Foil.Node.WebServer\\app\\processundefined' }
[2018-09-14 14:09:21.312] [ERROR] dateFileLog - Error: Password is not correct for userAID Admin.
    at callback_getUser (D:\work\Source\yujiang.Foil.Node.BizServer\biz\account\checkLogin.js:178:24)
    at D:\work\Source\yujiang.Foil.Node\src\yjError.js:129:4
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.safeCallback (D:\work\Source\yujiang.Foil.Node\src\yjError.js:128:11)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:142:11)
    at Query.<anonymous> (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:480:33)
    at bound (domain.js:280:14)
    at Query.runBound [as _callback] (domain.js:293:12)
    at Query.Sequence.end (D:\work\Source\yujiang.NodeFoil.Npm\mysql\lib\protocol\sequences\Sequence.js:88:24)
    at Query._handleFinalResultPacket (D:\work\Source\yujiang.NodeFoil.Npm\mysql\lib\protocol\sequences\Query.js:139:8)
[2018-09-14 14:09:21.329] [ERROR] dateFileLog - Error: Password is not correct for userAID Admin.
    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:37:34
    at Request.callback (D:\work\Source\yujiang.NodeFoil.Npm\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\yujiang.NodeFoil.Npm\superagent\lib\node\index.js:990:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
