[2018-10-24T10:29:32.754] [ERROR] dateFileLog - { Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '* from hmiprint_moni where UUID=NULL' at line 1
    at Query.Sequence._packetToError (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\work\Source\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\work\Source\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    --------------------
    at Protocol._enqueue (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\work\Source\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:474:24)
    at success (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:465:9)
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:148:12)
    at D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:89:11
    at Ping.onPing (D:\work\Source\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:301:14)
    at Ping.runBound [as _callback] (domain.js:314:12)
  code: 'ER_PARSE_ERROR',
  errno: 1064,
  sqlState: '42000',
  index: 0,
  sql: 'delete * from hmiprint_moni where UUID=?' }
[2018-10-24T10:29:32.759] [ERROR] dateFileLog - Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '* from hmiprint_moni where UUID=NULL' at line 1
    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
[2018-10-24T14:04:40.108] [ERROR] dateFileLog - Error: TypeError: Cannot read property &#39;length&#39; of undefined<br> &nbsp; &nbsp;at module.exports (D:\work\Source\toolsWeb\biz\HMIPrint\CNtranslator.{m}.js:15:31)<br> &nbsp; &nbsp;at buildData (D:\work\Source\yujiang.Foil.Node\src\yjMVC.js:187:6)<br> &nbsp; &nbsp;at D:\work\Source\yujiang.Foil.Node\src\yjMVC.js:129:5<br> &nbsp; &nbsp;at Object.module.exports.read (D:\work\Source\yujiang.Foil.Node\src\yjMVC.cache.js:78:4)<br> &nbsp; &nbsp;at loadData (D:\work\Source\yujiang.Foil.Node\src\yjMVC.js:123:15)<br> &nbsp; &nbsp;at rrnmv (D:\work\Source\yujiang.Foil.Node\src\yjMVC.js:120:2)<br> &nbsp; &nbsp;at D:\work\Source\yujiang.Foil.Node\src\yjMVC.js:223:4<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (D:\work\Source\node_modules\express\lib\router\layer.js:95:5)<br> &nbsp; &nbsp;at next (D:\work\Source\node_modules\express\lib\router\route.js:131:13)<br> &nbsp; &nbsp;at Route.dispatch (D:\work\Source\node_modules\express\lib\router\route.js:112:3)

    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
[2018-10-24T14:08:33.520] [ERROR] dateFileLog - { Error: ER_BAD_FIELD_ERROR: Unknown column 'Company' in 'where clause'
    at Query.Sequence._packetToError (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\work\Source\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\work\Source\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    --------------------
    at Protocol._enqueue (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\work\Source\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:474:24)
    at success (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:465:9)
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:148:12)
    at D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:89:11
    at Ping.onPing (D:\work\Source\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:301:14)
    at Ping.runBound [as _callback] (domain.js:314:12)
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlState: '42S22',
  index: 0,
  sql: 'SELECT DDKey,CN FROM hmiprint_moni WHERE Company=? AND MachType=? AND Control=?' }
[2018-10-24T14:08:33.523] [ERROR] dateFileLog - Error: ER_BAD_FIELD_ERROR: Unknown column 'Company' in 'where clause'
    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
[2018-10-24T14:11:38.873] [ERROR] dateFileLog - { Error: ER_BAD_FIELD_ERROR: Unknown column 'UUID' in 'order clause'
    at Query.Sequence._packetToError (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\work\Source\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\work\Source\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    --------------------
    at Protocol._enqueue (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\work\Source\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:474:24)
    at success (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:465:9)
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:148:12)
    at D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:89:11
    at Ping.onPing (D:\work\Source\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:301:14)
    at Ping.runBound [as _callback] (domain.js:314:12)
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlState: '42S22',
  index: 0,
  sql: 'SELECT * FROM hmiprint_moni order by UUID DESC' }
[2018-10-24T14:11:38.876] [ERROR] dateFileLog - Error: ER_BAD_FIELD_ERROR: Unknown column 'UUID' in 'order clause'
    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
[2018-10-24T14:15:53.929] [ERROR] dateFileLog - { Error: ER_BAD_FIELD_ERROR: Unknown column 'UUID' in 'order clause'
    at Query.Sequence._packetToError (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\work\Source\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\work\Source\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    --------------------
    at Protocol._enqueue (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\work\Source\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:474:24)
    at success (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:465:9)
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:148:12)
    at D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:89:11
    at Ping.onPing (D:\work\Source\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:301:14)
    at Ping.runBound [as _callback] (domain.js:314:12)
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlState: '42S22',
  index: 0,
  sql: 'SELECT * FROM hmiprint_moni order by UUID DESC' }
[2018-10-24T14:15:53.932] [ERROR] dateFileLog - Error: ER_BAD_FIELD_ERROR: Unknown column 'UUID' in 'order clause'
    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
[2018-10-24T14:40:39.362] [ERROR] dateFileLog - Error: ReferenceError: UUID is not defined<br> &nbsp; &nbsp;at module.exports (D:\work\Source\toolsWeb\biz\HMIPrint\moniDel.{post}.{m}.js:14:23)<br> &nbsp; &nbsp;at buildData (D:\work\Source\yujiang.Foil.Node\src\yjMVC.js:187:6)<br> &nbsp; &nbsp;at D:\work\Source\yujiang.Foil.Node\src\yjMVC.js:129:5<br> &nbsp; &nbsp;at Object.module.exports.read (D:\work\Source\yujiang.Foil.Node\src\yjMVC.cache.js:78:4)<br> &nbsp; &nbsp;at loadData (D:\work\Source\yujiang.Foil.Node\src\yjMVC.js:123:15)<br> &nbsp; &nbsp;at rrnmv (D:\work\Source\yujiang.Foil.Node\src\yjMVC.js:120:2)<br> &nbsp; &nbsp;at D:\work\Source\yujiang.Foil.Node\src\yjMVC.js:223:4<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (D:\work\Source\node_modules\express\lib\router\layer.js:95:5)<br> &nbsp; &nbsp;at next (D:\work\Source\node_modules\express\lib\router\route.js:131:13)<br> &nbsp; &nbsp;at Route.dispatch (D:\work\Source\node_modules\express\lib\router\route.js:112:3)

    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
[2018-10-24T14:43:58.465] [ERROR] dateFileLog - { Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '?' at line 1
    at Query.Sequence._packetToError (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\work\Source\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\work\Source\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    --------------------
    at Protocol._enqueue (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\work\Source\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:474:24)
    at success (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:465:9)
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:148:12)
    at D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:89:11
    at Ping.onPing (D:\work\Source\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:301:14)
    at Ping.runBound [as _callback] (domain.js:314:12)
  code: 'ER_PARSE_ERROR',
  errno: 1064,
  sqlState: '42000',
  index: 0,
  sql: 'UPDATE hmiprint_moni SET Company=?,MachType=?,Control=?,DDKey=?,CN=?,TW=?,EN=?,Visible=? WHERE UID=?' }
[2018-10-24T14:43:58.471] [ERROR] dateFileLog - Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '?' at line 1
    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
[2018-10-24T14:43:59.642] [ERROR] dateFileLog - { Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '?' at line 1
    at Query.Sequence._packetToError (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\work\Source\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\work\Source\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\work\Source\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    --------------------
    at Protocol._enqueue (D:\work\Source\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\work\Source\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:474:24)
    at success (D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:465:9)
    at Object.exports.safeSuccess (D:\work\Source\yujiang.Foil.Node\src\yjError.js:94:13)
    at Object.exports.handleResult (D:\work\Source\yujiang.Foil.Node\src\yjError.js:148:12)
    at D:\work\Source\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:89:11
    at Ping.onPing (D:\work\Source\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:301:14)
    at Ping.runBound [as _callback] (domain.js:314:12)
  code: 'ER_PARSE_ERROR',
  errno: 1064,
  sqlState: '42000',
  index: 0,
  sql: 'UPDATE hmiprint_moni SET Company=?,MachType=?,Control=?,DDKey=?,CN=?,TW=?,EN=?,Visible=? WHERE UID=?' }
[2018-10-24T14:43:59.645] [ERROR] dateFileLog - Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '?' at line 1
    at D:\work\Source\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\Source\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\Source\node_modules\superagent\lib\node\index.js:990:12)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
