[2018-09-11 09:57:36.991] [ERROR] dateFileLog - [Error: Not found this user.]
Error: Not found this user.
    at callback_getUser (D:\NB\yujiang.Foil.Node.BizServer\biz\account\checkLogin.js:106:17)
    at D:\NB\yujiang.Foil.Node\src\yjError.js:134:4
    at Object.exports.safeSuccess (D:\NB\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.safeCallback (D:\NB\yujiang.Foil.Node\src\yjError.js:133:11)
    at Object.exports.handleResult (D:\NB\yujiang.Foil.Node\src\yjError.js:148:11)
    at Query.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:202:38)
    at bound (domain.js:287:14)
    at Query.runBound [as _callback] (domain.js:300:12)
    at Query.Sequence.end (D:\NB\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
    at Query._handleFinalResultPacket (D:\NB\node_modules\mysql\lib\protocol\sequences\Query.js:143:8)
[2018-09-11 09:57:36.995] [ERROR] dateFileLog - [Error: 没有找到此用户。]
Error: 没有找到此用户。
    at Request.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireSuccess (D:\NB\node_modules\restler\lib\restler.js:220:12)
    at D:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.parsers.auto (D:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request.mixin._encode (D:\NB\node_modules\restler\lib\restler.js:195:29)
    at D:\NB\node_modules\restler\lib\restler.js:154:16
    at Request.mixin._decode (D:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (D:\NB\node_modules\restler\lib\restler.js:147:14)
[2018-09-11 09:57:40.987] [ERROR] dateFileLog - [Error: Not found this user.]
Error: Not found this user.
    at callback_getUser (D:\NB\yujiang.Foil.Node.BizServer\biz\account\checkLogin.js:106:17)
    at D:\NB\yujiang.Foil.Node\src\yjError.js:134:4
    at Object.exports.safeSuccess (D:\NB\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.safeCallback (D:\NB\yujiang.Foil.Node\src\yjError.js:133:11)
    at Object.exports.handleResult (D:\NB\yujiang.Foil.Node\src\yjError.js:148:11)
    at Query.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:202:38)
    at bound (domain.js:287:14)
    at Query.runBound [as _callback] (domain.js:300:12)
    at Query.Sequence.end (D:\NB\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
    at Query._handleFinalResultPacket (D:\NB\node_modules\mysql\lib\protocol\sequences\Query.js:143:8)
[2018-09-11 09:57:40.990] [ERROR] dateFileLog - [Error: 没有找到此用户。]
Error: 没有找到此用户。
    at Request.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireSuccess (D:\NB\node_modules\restler\lib\restler.js:220:12)
    at D:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.parsers.auto (D:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request.mixin._encode (D:\NB\node_modules\restler\lib\restler.js:195:29)
    at D:\NB\node_modules\restler\lib\restler.js:154:16
    at Request.mixin._decode (D:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (D:\NB\node_modules\restler\lib\restler.js:147:14)
[2018-09-11 10:06:09.855] [ERROR] dateFileLog - { [Error: ER_DUP_ENTRY: Duplicate entry '7YI002' for key 'UserAID'] code: 'ER_DUP_ENTRY', errno: 1062, sqlState: '23000', index: 0 }
Error: ER_DUP_ENTRY: Duplicate entry '7YI002' for key 'UserAID'
    at Query.Sequence._packetToError (D:\NB\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\NB\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\NB\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\NB\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:536:20)
    --------------------
    at Protocol._enqueue (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\NB\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:128:25)
    at getConnection.success (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:119:13)
    at Object.exports.safeSuccess (D:\NB\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.handleResult (D:\NB\yujiang.Foil.Node\src\yjError.js:154:12)
    at D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:57:11
    at Ping.onPing (D:\NB\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:287:14)
    at Ping.runBound [as _callback] (domain.js:300:12)
[2018-09-11 10:06:09.969] [ERROR] dateFileLog - [Error: ER_DUP_ENTRY: Duplicate entry '7YI002' for key 'UserAID']
Error: ER_DUP_ENTRY: Duplicate entry '7YI002' for key 'UserAID'
    at Request.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireSuccess (D:\NB\node_modules\restler\lib\restler.js:220:12)
    at D:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.parsers.auto (D:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request.mixin._encode (D:\NB\node_modules\restler\lib\restler.js:195:29)
    at D:\NB\node_modules\restler\lib\restler.js:154:16
    at Request.mixin._decode (D:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (D:\NB\node_modules\restler\lib\restler.js:147:14)
[2018-09-11 10:06:10.039] [ERROR] dateFileLog - { [Error: ER_DUP_ENTRY: Duplicate entry '7YI002' for key 'Acount'] code: 'ER_DUP_ENTRY', errno: 1062, sqlState: '23000', index: 0 }
Error: ER_DUP_ENTRY: Duplicate entry '7YI002' for key 'Acount'
    at Query.Sequence._packetToError (D:\NB\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\NB\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\NB\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\NB\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:536:20)
    --------------------
    at Protocol._enqueue (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\NB\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:128:25)
    at getConnection.success (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:119:13)
    at Object.exports.safeSuccess (D:\NB\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.handleResult (D:\NB\yujiang.Foil.Node\src\yjError.js:154:12)
    at D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:57:11
    at Ping.onPing (D:\NB\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:287:14)
    at Ping.runBound [as _callback] (domain.js:300:12)
[2018-09-11 10:06:10.040] [ERROR] dateFileLog - [Error: ER_DUP_ENTRY: Duplicate entry '7YI002' for key 'Acount']
Error: ER_DUP_ENTRY: Duplicate entry '7YI002' for key 'Acount'
    at Request.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireSuccess (D:\NB\node_modules\restler\lib\restler.js:220:12)
    at D:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.parsers.auto (D:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request.mixin._encode (D:\NB\node_modules\restler\lib\restler.js:195:29)
    at D:\NB\node_modules\restler\lib\restler.js:154:16
    at Request.mixin._decode (D:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (D:\NB\node_modules\restler\lib\restler.js:147:14)
[2018-09-11 10:06:14.046] [ERROR] dateFileLog - { [Error: ER_DUP_ENTRY: Duplicate entry '7YI002' for key 'Acount'] code: 'ER_DUP_ENTRY', errno: 1062, sqlState: '23000', index: 0 }
Error: ER_DUP_ENTRY: Duplicate entry '7YI002' for key 'Acount'
    at Query.Sequence._packetToError (D:\NB\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\NB\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\NB\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\NB\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:536:20)
    --------------------
    at Protocol._enqueue (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\NB\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:128:25)
    at getConnection.success (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:119:13)
    at Object.exports.safeSuccess (D:\NB\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.handleResult (D:\NB\yujiang.Foil.Node\src\yjError.js:154:12)
    at D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:57:11
    at Ping.onPing (D:\NB\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:287:14)
    at Ping.runBound [as _callback] (domain.js:300:12)
[2018-09-11 10:06:14.048] [ERROR] dateFileLog - [Error: ER_DUP_ENTRY: Duplicate entry '7YI002' for key 'Acount']
Error: ER_DUP_ENTRY: Duplicate entry '7YI002' for key 'Acount'
    at Request.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireSuccess (D:\NB\node_modules\restler\lib\restler.js:220:12)
    at D:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.parsers.auto (D:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request.mixin._encode (D:\NB\node_modules\restler\lib\restler.js:195:29)
    at D:\NB\node_modules\restler\lib\restler.js:154:16
    at Request.mixin._decode (D:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (D:\NB\node_modules\restler\lib\restler.js:147:14)
[2018-09-11 10:06:14.098] [ERROR] dateFileLog - { [Error: ER_DUP_ENTRY: Duplicate entry '7YI002' for key 'UserAID'] code: 'ER_DUP_ENTRY', errno: 1062, sqlState: '23000', index: 0 }
Error: ER_DUP_ENTRY: Duplicate entry '7YI002' for key 'UserAID'
    at Query.Sequence._packetToError (D:\NB\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\NB\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\NB\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\NB\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:536:20)
    --------------------
    at Protocol._enqueue (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\NB\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:128:25)
    at getConnection.success (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:119:13)
    at Object.exports.safeSuccess (D:\NB\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.handleResult (D:\NB\yujiang.Foil.Node\src\yjError.js:154:12)
    at D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:57:11
    at Ping.onPing (D:\NB\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:287:14)
    at Ping.runBound [as _callback] (domain.js:300:12)
[2018-09-11 10:06:14.100] [ERROR] dateFileLog - [Error: ER_DUP_ENTRY: Duplicate entry '7YI002' for key 'UserAID']
Error: ER_DUP_ENTRY: Duplicate entry '7YI002' for key 'UserAID'
    at Request.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireSuccess (D:\NB\node_modules\restler\lib\restler.js:220:12)
    at D:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.parsers.auto (D:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request.mixin._encode (D:\NB\node_modules\restler\lib\restler.js:195:29)
    at D:\NB\node_modules\restler\lib\restler.js:154:16
    at Request.mixin._decode (D:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (D:\NB\node_modules\restler\lib\restler.js:147:14)
