[2018-07-30 10:44:11.162] [ERROR] dateFileLog - [Error: TypeError: Cannot read property &#39;MKID&#39; of undefined<br> &nbsp; &nbsp;at module.exports (D:\NB\tm.FGEMS\bizServer\biz\MSAgent\logInfo.{post}.{m}.js:4:35)<br> &nbsp; &nbsp;at buildData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:256:6)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:198:5<br> &nbsp; &nbsp;at Object.module.exports.read (D:\NB\yujiang.Foil.Node\src\yjMVC.cache.js:80:4)<br> &nbsp; &nbsp;at loadData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:192:15)<br> &nbsp; &nbsp;at rrnmv (D:\NB\yujiang.Foil.Node\src\yjMVC.js:188:3)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:290:4<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (D:\NB\node_modules\express\lib\router\layer.js:95:5)<br> &nbsp; &nbsp;at next (D:\NB\node_modules\express\lib\router\route.js:131:13)<br> &nbsp; &nbsp;at Route.dispatch (D:\NB\node_modules\express\lib\router\route.js:112:3)
]
Error: TypeError: Cannot read property &#39;MKID&#39; of undefined<br> &nbsp; &nbsp;at module.exports (D:\NB\tm.FGEMS\bizServer\biz\MSAgent\logInfo.{post}.{m}.js:4:35)<br> &nbsp; &nbsp;at buildData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:256:6)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:198:5<br> &nbsp; &nbsp;at Object.module.exports.read (D:\NB\yujiang.Foil.Node\src\yjMVC.cache.js:80:4)<br> &nbsp; &nbsp;at loadData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:192:15)<br> &nbsp; &nbsp;at rrnmv (D:\NB\yujiang.Foil.Node\src\yjMVC.js:188:3)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:290:4<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (D:\NB\node_modules\express\lib\router\layer.js:95:5)<br> &nbsp; &nbsp;at next (D:\NB\node_modules\express\lib\router\route.js:131:13)<br> &nbsp; &nbsp;at Route.dispatch (D:\NB\node_modules\express\lib\router\route.js:112:3)

    at Request.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireSuccess (D:\NB\node_modules\restler\lib\restler.js:220:12)
    at D:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.parsers.auto (D:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request.mixin._encode (D:\NB\node_modules\restler\lib\restler.js:195:29)
    at D:\NB\node_modules\restler\lib\restler.js:154:16
    at Request.mixin._decode (D:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (D:\NB\node_modules\restler\lib\restler.js:147:14)
[2018-07-30 18:10:23.549] [ERROR] dateFileLog - { [Error: ER_WRONG_VALUE_COUNT_ON_ROW: Column count doesn't match value count at row 1]
  code: 'ER_WRONG_VALUE_COUNT_ON_ROW',
  errno: 1136,
  sqlState: '21S01',
  index: 0 }
Error: ER_WRONG_VALUE_COUNT_ON_ROW: Column count doesn't match value count at row 1
    at Query.Sequence._packetToError (D:\NB\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\NB\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\NB\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\NB\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    --------------------
    at Protocol._enqueue (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\NB\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:128:25)
    at getConnection.success (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:119:13)
    at Object.exports.safeSuccess (D:\NB\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.handleResult (D:\NB\yujiang.Foil.Node\src\yjError.js:154:12)
    at D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:57:11
    at Ping.onPing (D:\NB\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:287:14)
    at Ping.runBound [as _callback] (domain.js:300:12)
[2018-07-30 18:10:23.553] [ERROR] dateFileLog - [Error: ER_WRONG_VALUE_COUNT_ON_ROW: Column count doesn't match value count at row 1]
Error: ER_WRONG_VALUE_COUNT_ON_ROW: Column count doesn't match value count at row 1
    at Request.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireSuccess (D:\NB\node_modules\restler\lib\restler.js:220:12)
    at D:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.parsers.auto (D:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request.mixin._encode (D:\NB\node_modules\restler\lib\restler.js:195:29)
    at D:\NB\node_modules\restler\lib\restler.js:154:16
    at Request.mixin._decode (D:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (D:\NB\node_modules\restler\lib\restler.js:147:14)
[2018-07-30 18:11:11.326] [ERROR] dateFileLog - [Error: ReferenceError: ID is not defined<br> &nbsp; &nbsp;at module.exports (D:\NB\tm.FGEMS\bizServer\biz\MSAgent\logInfo.{post}.{m}.js:22:23)<br> &nbsp; &nbsp;at buildData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:256:6)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:198:5<br> &nbsp; &nbsp;at Object.module.exports.read (D:\NB\yujiang.Foil.Node\src\yjMVC.cache.js:80:4)<br> &nbsp; &nbsp;at loadData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:192:15)<br> &nbsp; &nbsp;at rrnmv (D:\NB\yujiang.Foil.Node\src\yjMVC.js:188:3)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:290:4<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (D:\NB\node_modules\express\lib\router\layer.js:95:5)<br> &nbsp; &nbsp;at next (D:\NB\node_modules\express\lib\router\route.js:131:13)<br> &nbsp; &nbsp;at Route.dispatch (D:\NB\node_modules\express\lib\router\route.js:112:3)
]
Error: ReferenceError: ID is not defined<br> &nbsp; &nbsp;at module.exports (D:\NB\tm.FGEMS\bizServer\biz\MSAgent\logInfo.{post}.{m}.js:22:23)<br> &nbsp; &nbsp;at buildData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:256:6)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:198:5<br> &nbsp; &nbsp;at Object.module.exports.read (D:\NB\yujiang.Foil.Node\src\yjMVC.cache.js:80:4)<br> &nbsp; &nbsp;at loadData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:192:15)<br> &nbsp; &nbsp;at rrnmv (D:\NB\yujiang.Foil.Node\src\yjMVC.js:188:3)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:290:4<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (D:\NB\node_modules\express\lib\router\layer.js:95:5)<br> &nbsp; &nbsp;at next (D:\NB\node_modules\express\lib\router\route.js:131:13)<br> &nbsp; &nbsp;at Route.dispatch (D:\NB\node_modules\express\lib\router\route.js:112:3)

    at Request.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireSuccess (D:\NB\node_modules\restler\lib\restler.js:220:12)
    at D:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.parsers.auto (D:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request.mixin._encode (D:\NB\node_modules\restler\lib\restler.js:195:29)
    at D:\NB\node_modules\restler\lib\restler.js:154:16
    at Request.mixin._decode (D:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (D:\NB\node_modules\restler\lib\restler.js:147:14)
[2018-07-30 18:12:17.783] [ERROR] dateFileLog - [Error: ReferenceError: SID is not defined<br> &nbsp; &nbsp;at module.exports (D:\NB\tm.FGEMS\bizServer\biz\MSAgent\logInfo.{post}.{m}.js:22:23)<br> &nbsp; &nbsp;at buildData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:256:6)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:198:5<br> &nbsp; &nbsp;at Object.module.exports.read (D:\NB\yujiang.Foil.Node\src\yjMVC.cache.js:80:4)<br> &nbsp; &nbsp;at loadData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:192:15)<br> &nbsp; &nbsp;at rrnmv (D:\NB\yujiang.Foil.Node\src\yjMVC.js:188:3)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:290:4<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (D:\NB\node_modules\express\lib\router\layer.js:95:5)<br> &nbsp; &nbsp;at next (D:\NB\node_modules\express\lib\router\route.js:131:13)<br> &nbsp; &nbsp;at Route.dispatch (D:\NB\node_modules\express\lib\router\route.js:112:3)
]
Error: ReferenceError: SID is not defined<br> &nbsp; &nbsp;at module.exports (D:\NB\tm.FGEMS\bizServer\biz\MSAgent\logInfo.{post}.{m}.js:22:23)<br> &nbsp; &nbsp;at buildData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:256:6)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:198:5<br> &nbsp; &nbsp;at Object.module.exports.read (D:\NB\yujiang.Foil.Node\src\yjMVC.cache.js:80:4)<br> &nbsp; &nbsp;at loadData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:192:15)<br> &nbsp; &nbsp;at rrnmv (D:\NB\yujiang.Foil.Node\src\yjMVC.js:188:3)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:290:4<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (D:\NB\node_modules\express\lib\router\layer.js:95:5)<br> &nbsp; &nbsp;at next (D:\NB\node_modules\express\lib\router\route.js:131:13)<br> &nbsp; &nbsp;at Route.dispatch (D:\NB\node_modules\express\lib\router\route.js:112:3)

    at Request.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireSuccess (D:\NB\node_modules\restler\lib\restler.js:220:12)
    at D:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.parsers.auto (D:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request.mixin._encode (D:\NB\node_modules\restler\lib\restler.js:195:29)
    at D:\NB\node_modules\restler\lib\restler.js:154:16
    at Request.mixin._decode (D:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (D:\NB\node_modules\restler\lib\restler.js:147:14)
[2018-07-30 18:32:28.775] [ERROR] dateFileLog - { [Error: ER_WRONG_VALUE_COUNT_ON_ROW: Column count doesn't match value count at row 1]
  code: 'ER_WRONG_VALUE_COUNT_ON_ROW',
  errno: 1136,
  sqlState: '21S01',
  index: 0 }
Error: ER_WRONG_VALUE_COUNT_ON_ROW: Column count doesn't match value count at row 1
    at Query.Sequence._packetToError (D:\NB\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\NB\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\NB\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\NB\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    --------------------
    at Protocol._enqueue (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\NB\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:128:25)
    at getConnection.success (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:119:13)
    at Object.exports.safeSuccess (D:\NB\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.handleResult (D:\NB\yujiang.Foil.Node\src\yjError.js:154:12)
    at D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:57:11
    at Ping.onPing (D:\NB\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:287:14)
    at Ping.runBound [as _callback] (domain.js:300:12)
[2018-07-30 18:32:28.778] [ERROR] dateFileLog - [Error: ER_WRONG_VALUE_COUNT_ON_ROW: Column count doesn't match value count at row 1]
Error: ER_WRONG_VALUE_COUNT_ON_ROW: Column count doesn't match value count at row 1
    at Request.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireSuccess (D:\NB\node_modules\restler\lib\restler.js:220:12)
    at D:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.parsers.auto (D:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request.mixin._encode (D:\NB\node_modules\restler\lib\restler.js:195:29)
    at D:\NB\node_modules\restler\lib\restler.js:154:16
    at Request.mixin._decode (D:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (D:\NB\node_modules\restler\lib\restler.js:147:14)
[2018-07-30 18:33:57.471] [ERROR] dateFileLog - [Error: ReferenceError: SID is not defined<br> &nbsp; &nbsp;at module.exports (D:\NB\tm.FGEMS\bizServer\biz\MSAgent\logInfo.{post}.{m}.js:22:23)<br> &nbsp; &nbsp;at buildData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:256:6)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:198:5<br> &nbsp; &nbsp;at Object.module.exports.read (D:\NB\yujiang.Foil.Node\src\yjMVC.cache.js:80:4)<br> &nbsp; &nbsp;at loadData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:192:15)<br> &nbsp; &nbsp;at rrnmv (D:\NB\yujiang.Foil.Node\src\yjMVC.js:188:3)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:290:4<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (D:\NB\node_modules\express\lib\router\layer.js:95:5)<br> &nbsp; &nbsp;at next (D:\NB\node_modules\express\lib\router\route.js:131:13)<br> &nbsp; &nbsp;at Route.dispatch (D:\NB\node_modules\express\lib\router\route.js:112:3)
]
Error: ReferenceError: SID is not defined<br> &nbsp; &nbsp;at module.exports (D:\NB\tm.FGEMS\bizServer\biz\MSAgent\logInfo.{post}.{m}.js:22:23)<br> &nbsp; &nbsp;at buildData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:256:6)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:198:5<br> &nbsp; &nbsp;at Object.module.exports.read (D:\NB\yujiang.Foil.Node\src\yjMVC.cache.js:80:4)<br> &nbsp; &nbsp;at loadData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:192:15)<br> &nbsp; &nbsp;at rrnmv (D:\NB\yujiang.Foil.Node\src\yjMVC.js:188:3)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:290:4<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (D:\NB\node_modules\express\lib\router\layer.js:95:5)<br> &nbsp; &nbsp;at next (D:\NB\node_modules\express\lib\router\route.js:131:13)<br> &nbsp; &nbsp;at Route.dispatch (D:\NB\node_modules\express\lib\router\route.js:112:3)

    at Request.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireSuccess (D:\NB\node_modules\restler\lib\restler.js:220:12)
    at D:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.parsers.auto (D:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request.mixin._encode (D:\NB\node_modules\restler\lib\restler.js:195:29)
    at D:\NB\node_modules\restler\lib\restler.js:154:16
    at Request.mixin._decode (D:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (D:\NB\node_modules\restler\lib\restler.js:147:14)
[2018-07-30 18:34:42.225] [ERROR] dateFileLog - { [Error: ER_WRONG_VALUE_COUNT_ON_ROW: Column count doesn't match value count at row 1]
  code: 'ER_WRONG_VALUE_COUNT_ON_ROW',
  errno: 1136,
  sqlState: '21S01',
  index: 0 }
Error: ER_WRONG_VALUE_COUNT_ON_ROW: Column count doesn't match value count at row 1
    at Query.Sequence._packetToError (D:\NB\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\NB\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\NB\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\NB\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    --------------------
    at Protocol._enqueue (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\NB\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:128:25)
    at getConnection.success (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:119:13)
    at Object.exports.safeSuccess (D:\NB\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.handleResult (D:\NB\yujiang.Foil.Node\src\yjError.js:154:12)
    at D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:57:11
    at Ping.onPing (D:\NB\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:287:14)
    at Ping.runBound [as _callback] (domain.js:300:12)
[2018-07-30 18:34:42.234] [ERROR] dateFileLog - [Error: ER_WRONG_VALUE_COUNT_ON_ROW: Column count doesn't match value count at row 1]
Error: ER_WRONG_VALUE_COUNT_ON_ROW: Column count doesn't match value count at row 1
    at Request.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireSuccess (D:\NB\node_modules\restler\lib\restler.js:220:12)
    at D:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.parsers.auto (D:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request.mixin._encode (D:\NB\node_modules\restler\lib\restler.js:195:29)
    at D:\NB\node_modules\restler\lib\restler.js:154:16
    at Request.mixin._decode (D:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (D:\NB\node_modules\restler\lib\restler.js:147:14)
