[2018-08-14 09:39:59.015] [ERROR] dateFileLog - [Error: Password is not correct.]
Error: Password is not correct.
    at callback_getUser (D:\NB\yujiang.Foil.Node.BizServer\biz\account\checkLogin.js:148:17)
    at D:\NB\yujiang.Foil.Node\src\yjError.js:134:4
    at Object.exports.safeSuccess (D:\NB\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.safeCallback (D:\NB\yujiang.Foil.Node\src\yjError.js:133:11)
    at Object.exports.handleResult (D:\NB\yujiang.Foil.Node\src\yjError.js:148:11)
    at Query.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:202:38)
    at bound (domain.js:287:14)
    at Query.runBound [as _callback] (domain.js:300:12)
    at Query.Sequence.end (D:\NB\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
    at Query._handleFinalResultPacket (D:\NB\node_modules\mysql\lib\protocol\sequences\Query.js:143:8)
[2018-08-14 09:39:59.023] [ERROR] dateFileLog - [Error: 密码不对。]
Error: 密码不对。
    at Request.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireSuccess (D:\NB\node_modules\restler\lib\restler.js:220:12)
    at D:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.parsers.auto (D:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request.mixin._encode (D:\NB\node_modules\restler\lib\restler.js:195:29)
    at D:\NB\node_modules\restler\lib\restler.js:154:16
    at Request.mixin._decode (D:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (D:\NB\node_modules\restler\lib\restler.js:147:14)
[2018-08-14 09:40:24.542] [ERROR] dateFileLog - { [Error: ER_DUP_ENTRY: Duplicate entry '7HD001' for key 'UserAID'] code: 'ER_DUP_ENTRY', errno: 1062, sqlState: '23000', index: 0 }
Error: ER_DUP_ENTRY: Duplicate entry '7HD001' for key 'UserAID'
    at Query.Sequence._packetToError (D:\NB\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\NB\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\NB\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\NB\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    --------------------
    at Protocol._enqueue (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\NB\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:128:25)
    at getConnection.success (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:119:13)
    at Object.exports.safeSuccess (D:\NB\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.handleResult (D:\NB\yujiang.Foil.Node\src\yjError.js:154:12)
    at D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:57:11
    at Ping.onPing (D:\NB\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:287:14)
    at Ping.runBound [as _callback] (domain.js:300:12)
[2018-08-14 09:40:24.545] [ERROR] dateFileLog - [Error: ER_DUP_ENTRY: Duplicate entry '7HD001' for key 'UserAID']
Error: ER_DUP_ENTRY: Duplicate entry '7HD001' for key 'UserAID'
    at Request.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireSuccess (D:\NB\node_modules\restler\lib\restler.js:220:12)
    at D:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.parsers.auto (D:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request.mixin._encode (D:\NB\node_modules\restler\lib\restler.js:195:29)
    at D:\NB\node_modules\restler\lib\restler.js:154:16
    at Request.mixin._decode (D:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (D:\NB\node_modules\restler\lib\restler.js:147:14)
[2018-08-14 09:44:11.039] [ERROR] dateFileLog - { [Error: ER_DUP_ENTRY: Duplicate entry '0EJ001' for key 'UserAID'] code: 'ER_DUP_ENTRY', errno: 1062, sqlState: '23000', index: 0 }
Error: ER_DUP_ENTRY: Duplicate entry '0EJ001' for key 'UserAID'
    at Query.Sequence._packetToError (D:\NB\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\NB\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\NB\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\NB\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    --------------------
    at Protocol._enqueue (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\NB\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:128:25)
    at getConnection.success (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:119:13)
    at Object.exports.safeSuccess (D:\NB\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.handleResult (D:\NB\yujiang.Foil.Node\src\yjError.js:154:12)
    at D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:57:11
    at Ping.onPing (D:\NB\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:287:14)
    at Ping.runBound [as _callback] (domain.js:300:12)
[2018-08-14 09:44:11.045] [ERROR] dateFileLog - [Error: ER_DUP_ENTRY: Duplicate entry '0EJ001' for key 'UserAID']
Error: ER_DUP_ENTRY: Duplicate entry '0EJ001' for key 'UserAID'
    at Request.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireSuccess (D:\NB\node_modules\restler\lib\restler.js:220:12)
    at D:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.parsers.auto (D:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request.mixin._encode (D:\NB\node_modules\restler\lib\restler.js:195:29)
    at D:\NB\node_modules\restler\lib\restler.js:154:16
    at Request.mixin._decode (D:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (D:\NB\node_modules\restler\lib\restler.js:147:14)
[2018-08-14 09:50:48.692] [ERROR] dateFileLog - { [Error: ER_DUP_ENTRY: Duplicate entry '7AE001' for key 'UserAID'] code: 'ER_DUP_ENTRY', errno: 1062, sqlState: '23000', index: 0 }
Error: ER_DUP_ENTRY: Duplicate entry '7AE001' for key 'UserAID'
    at Query.Sequence._packetToError (D:\NB\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\NB\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\NB\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\NB\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    --------------------
    at Protocol._enqueue (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\NB\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:128:25)
    at getConnection.success (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:119:13)
    at Object.exports.safeSuccess (D:\NB\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.handleResult (D:\NB\yujiang.Foil.Node\src\yjError.js:154:12)
    at D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:57:11
    at Ping.onPing (D:\NB\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:287:14)
    at Ping.runBound [as _callback] (domain.js:300:12)
[2018-08-14 09:50:48.695] [ERROR] dateFileLog - [Error: ER_DUP_ENTRY: Duplicate entry '7AE001' for key 'UserAID']
Error: ER_DUP_ENTRY: Duplicate entry '7AE001' for key 'UserAID'
    at Request.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireSuccess (D:\NB\node_modules\restler\lib\restler.js:220:12)
    at D:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.parsers.auto (D:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request.mixin._encode (D:\NB\node_modules\restler\lib\restler.js:195:29)
    at D:\NB\node_modules\restler\lib\restler.js:154:16
    at Request.mixin._decode (D:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (D:\NB\node_modules\restler\lib\restler.js:147:14)
[2018-08-14 16:29:40.237] [ERROR] dateFileLog - { [Error: ER_DUP_ENTRY: Duplicate entry '2147483647' for key 'PRIMARY'] code: 'ER_DUP_ENTRY', errno: 1062, sqlState: '23000', index: 0 }
Error: ER_DUP_ENTRY: Duplicate entry '2147483647' for key 'PRIMARY'
    at Query.Sequence._packetToError (D:\NB\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\NB\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\NB\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\NB\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    --------------------
    at Protocol._enqueue (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\NB\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:128:25)
    at getConnection.success (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:119:13)
    at Object.exports.safeSuccess (D:\NB\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.handleResult (D:\NB\yujiang.Foil.Node\src\yjError.js:154:12)
    at D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:57:11
    at Ping.onPing (D:\NB\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:287:14)
    at Ping.runBound [as _callback] (domain.js:300:12)
[2018-08-14 16:29:40.241] [ERROR] dateFileLog - [Error: ER_DUP_ENTRY: Duplicate entry '2147483647' for key 'PRIMARY']
Error: ER_DUP_ENTRY: Duplicate entry '2147483647' for key 'PRIMARY'
    at Request.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireSuccess (D:\NB\node_modules\restler\lib\restler.js:220:12)
    at D:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.parsers.auto (D:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request.mixin._encode (D:\NB\node_modules\restler\lib\restler.js:195:29)
    at D:\NB\node_modules\restler\lib\restler.js:154:16
    at Request.mixin._decode (D:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (D:\NB\node_modules\restler\lib\restler.js:147:14)
[2018-08-14 16:29:40.246] [ERROR] dateFileLog - [Error: Can't set headers after they are sent.]
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:344:11)
    at ServerResponse.header (D:\NB\node_modules\express\lib\response.js:718:10)
    at ServerResponse.send (D:\NB\node_modules\express\lib\response.js:163:12)
    at ServerResponse.json (D:\NB\node_modules\express\lib\response.js:249:15)
    at ServerResponse.send (D:\NB\node_modules\express\lib\response.js:151:21)
    at proc_success (D:\NB\yujiang.Foil.Node\src\yjMVC.js:111:13)
    at Object.sender.success (D:\NB\yujiang.Foil.Node\src\yjMVC.js:239:8)
    at yjDBService.exec.success (D:\NB\tm.FGEMS\bizServer\biz\MSInfo\addUsers.{post}.{m}.js:46:17)
    at Object.exports.safeSuccess (D:\NB\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.handleResult (D:\NB\yujiang.Foil.Node\src\yjError.js:154:12)
[2018-08-14 16:32:14.893] [ERROR] dateFileLog - { [Error: ER_DUP_ENTRY: Duplicate entry '2147483647-190' for key 'PRIMARY'] code: 'ER_DUP_ENTRY', errno: 1062, sqlState: '23000', index: 0 }
Error: ER_DUP_ENTRY: Duplicate entry '2147483647-190' for key 'PRIMARY'
    at Query.Sequence._packetToError (D:\NB\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\NB\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\NB\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\NB\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    --------------------
    at Protocol._enqueue (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\NB\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:128:25)
    at getConnection.success (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:119:13)
    at Object.exports.safeSuccess (D:\NB\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.handleResult (D:\NB\yujiang.Foil.Node\src\yjError.js:154:12)
    at D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:57:11
    at Ping.onPing (D:\NB\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:287:14)
    at Ping.runBound [as _callback] (domain.js:300:12)
[2018-08-14 16:32:14.896] [ERROR] dateFileLog - { [Error: ER_DUP_ENTRY: Duplicate entry '2147483647' for key 'PRIMARY'] code: 'ER_DUP_ENTRY', errno: 1062, sqlState: '23000', index: 0 }
Error: ER_DUP_ENTRY: Duplicate entry '2147483647' for key 'PRIMARY'
    at Query.Sequence._packetToError (D:\NB\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\NB\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\NB\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\NB\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    --------------------
    at Protocol._enqueue (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\NB\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:128:25)
    at getConnection.success (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:119:13)
    at Object.exports.safeSuccess (D:\NB\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.handleResult (D:\NB\yujiang.Foil.Node\src\yjError.js:154:12)
    at D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:57:11
    at Ping.onPing (D:\NB\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:287:14)
    at Ping.runBound [as _callback] (domain.js:300:12)
[2018-08-14 16:32:14.904] [ERROR] dateFileLog - [Error: ER_DUP_ENTRY: Duplicate entry '2147483647-190' for key 'PRIMARY']
Error: ER_DUP_ENTRY: Duplicate entry '2147483647-190' for key 'PRIMARY'
    at Request.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireSuccess (D:\NB\node_modules\restler\lib\restler.js:220:12)
    at D:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.parsers.auto (D:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request.mixin._encode (D:\NB\node_modules\restler\lib\restler.js:195:29)
    at D:\NB\node_modules\restler\lib\restler.js:154:16
    at Request.mixin._decode (D:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (D:\NB\node_modules\restler\lib\restler.js:147:14)
[2018-08-14 16:34:08.568] [ERROR] dateFileLog - [Error: Can't set headers after they are sent.]
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:344:11)
    at ServerResponse.header (D:\NB\node_modules\express\lib\response.js:718:10)
    at ServerResponse.send (D:\NB\node_modules\express\lib\response.js:163:12)
    at ServerResponse.json (D:\NB\node_modules\express\lib\response.js:249:15)
    at ServerResponse.send (D:\NB\node_modules\express\lib\response.js:151:21)
    at proc_success (D:\NB\yujiang.Foil.Node\src\yjMVC.js:111:13)
    at Object.sender.success (D:\NB\yujiang.Foil.Node\src\yjMVC.js:239:8)
    at yjDBService.exec.success (D:\NB\tm.FGEMS\bizServer\biz\MSInfo\addUsers.{post}.{m}.js:61:17)
    at Object.exports.safeSuccess (D:\NB\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.handleResult (D:\NB\yujiang.Foil.Node\src\yjError.js:154:12)
[2018-08-14 16:35:35.400] [ERROR] dateFileLog - { [Error: ER_DUP_ENTRY: Duplicate entry '20-190' for key 'PRIMARY'] code: 'ER_DUP_ENTRY', errno: 1062, sqlState: '23000', index: 0 }
Error: ER_DUP_ENTRY: Duplicate entry '20-190' for key 'PRIMARY'
    at Query.Sequence._packetToError (D:\NB\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\NB\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\NB\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\NB\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    --------------------
    at Protocol._enqueue (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\NB\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:128:25)
    at getConnection.success (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:119:13)
    at Object.exports.safeSuccess (D:\NB\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.handleResult (D:\NB\yujiang.Foil.Node\src\yjError.js:154:12)
    at D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:57:11
    at Ping.onPing (D:\NB\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:287:14)
    at Ping.runBound [as _callback] (domain.js:300:12)
[2018-08-14 16:35:35.404] [ERROR] dateFileLog - [Error: ER_DUP_ENTRY: Duplicate entry '20-190' for key 'PRIMARY']
Error: ER_DUP_ENTRY: Duplicate entry '20-190' for key 'PRIMARY'
    at Request.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireSuccess (D:\NB\node_modules\restler\lib\restler.js:220:12)
    at D:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.parsers.auto (D:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request.mixin._encode (D:\NB\node_modules\restler\lib\restler.js:195:29)
    at D:\NB\node_modules\restler\lib\restler.js:154:16
    at Request.mixin._decode (D:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (D:\NB\node_modules\restler\lib\restler.js:147:14)
[2018-08-14 16:35:35.465] [ERROR] dateFileLog - [Error: Can't set headers after they are sent.]
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:344:11)
    at ServerResponse.header (D:\NB\node_modules\express\lib\response.js:718:10)
    at ServerResponse.send (D:\NB\node_modules\express\lib\response.js:163:12)
    at ServerResponse.json (D:\NB\node_modules\express\lib\response.js:249:15)
    at ServerResponse.send (D:\NB\node_modules\express\lib\response.js:151:21)
    at proc_success (D:\NB\yujiang.Foil.Node\src\yjMVC.js:111:13)
    at Object.sender.success (D:\NB\yujiang.Foil.Node\src\yjMVC.js:239:8)
    at yjDBService.exec.success (D:\NB\tm.FGEMS\bizServer\biz\MSInfo\addUsers.{post}.{m}.js:44:17)
    at Object.exports.safeSuccess (D:\NB\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.handleResult (D:\NB\yujiang.Foil.Node\src\yjError.js:154:12)
[2018-08-14 16:42:14.950] [ERROR] dateFileLog - { [Error: HA_ERR_AUTOINC_ERANGE: Out of range value for column 'UserOID' at row 1]
  code: 'HA_ERR_AUTOINC_ERANGE',
  errno: 167,
  sqlState: '22003',
  index: 0 }
Error: HA_ERR_AUTOINC_ERANGE: Out of range value for column 'UserOID' at row 1
    at Query.Sequence._packetToError (D:\NB\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\NB\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\NB\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\NB\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    --------------------
    at Protocol._enqueue (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\NB\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:128:25)
    at getConnection.success (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:119:13)
    at Object.exports.safeSuccess (D:\NB\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.handleResult (D:\NB\yujiang.Foil.Node\src\yjError.js:154:12)
    at D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:57:11
    at Ping.onPing (D:\NB\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:287:14)
    at Ping.runBound [as _callback] (domain.js:300:12)
[2018-08-14 16:42:14.953] [ERROR] dateFileLog - [Error: HA_ERR_AUTOINC_ERANGE: Out of range value for column 'UserOID' at row 1]
Error: HA_ERR_AUTOINC_ERANGE: Out of range value for column 'UserOID' at row 1
    at Request.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireSuccess (D:\NB\node_modules\restler\lib\restler.js:220:12)
    at D:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.parsers.auto (D:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request.mixin._encode (D:\NB\node_modules\restler\lib\restler.js:195:29)
    at D:\NB\node_modules\restler\lib\restler.js:154:16
    at Request.mixin._decode (D:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (D:\NB\node_modules\restler\lib\restler.js:147:14)
[2018-08-14 16:42:14.981] [ERROR] dateFileLog - [Error: Can't set headers after they are sent.]
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:344:11)
    at ServerResponse.header (D:\NB\node_modules\express\lib\response.js:718:10)
    at ServerResponse.send (D:\NB\node_modules\express\lib\response.js:163:12)
    at ServerResponse.json (D:\NB\node_modules\express\lib\response.js:249:15)
    at ServerResponse.send (D:\NB\node_modules\express\lib\response.js:151:21)
    at proc_success (D:\NB\yujiang.Foil.Node\src\yjMVC.js:111:13)
    at Object.sender.success (D:\NB\yujiang.Foil.Node\src\yjMVC.js:239:8)
    at yjDBService.exec.success (D:\NB\tm.FGEMS\bizServer\biz\MSInfo\addUsers.{post}.{m}.js:61:17)
    at Object.exports.safeSuccess (D:\NB\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.handleResult (D:\NB\yujiang.Foil.Node\src\yjError.js:154:12)
[2018-08-14 16:56:42.473] [ERROR] dateFileLog - { [Error: ER_DUP_ENTRY: Duplicate entry '0-190' for key 'PRIMARY'] code: 'ER_DUP_ENTRY', errno: 1062, sqlState: '23000', index: 0 }
Error: ER_DUP_ENTRY: Duplicate entry '0-190' for key 'PRIMARY'
    at Query.Sequence._packetToError (D:\NB\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\NB\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\NB\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\NB\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:536:20)
    --------------------
    at Protocol._enqueue (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\NB\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:128:25)
    at getConnection.success (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:119:13)
    at Object.exports.safeSuccess (D:\NB\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.handleResult (D:\NB\yujiang.Foil.Node\src\yjError.js:154:12)
    at D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:57:11
    at Ping.onPing (D:\NB\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:287:14)
    at Ping.runBound [as _callback] (domain.js:300:12)
[2018-08-14 16:56:42.476] [ERROR] dateFileLog - { [Error: HA_ERR_AUTOINC_ERANGE: Out of range value for column 'UserOID' at row 1]
  code: 'HA_ERR_AUTOINC_ERANGE',
  errno: 167,
  sqlState: '22003',
  index: 0 }
Error: HA_ERR_AUTOINC_ERANGE: Out of range value for column 'UserOID' at row 1
    at Query.Sequence._packetToError (D:\NB\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\NB\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\NB\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\NB\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:536:20)
    --------------------
    at Protocol._enqueue (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\NB\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:128:25)
    at getConnection.success (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:119:13)
    at Object.exports.safeSuccess (D:\NB\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.handleResult (D:\NB\yujiang.Foil.Node\src\yjError.js:154:12)
    at D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:57:11
    at Ping.onPing (D:\NB\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:287:14)
    at Ping.runBound [as _callback] (domain.js:300:12)
[2018-08-14 16:56:42.478] [ERROR] dateFileLog - [Error: ER_DUP_ENTRY: Duplicate entry '0-190' for key 'PRIMARY']
Error: ER_DUP_ENTRY: Duplicate entry '0-190' for key 'PRIMARY'
    at Request.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireSuccess (D:\NB\node_modules\restler\lib\restler.js:220:12)
    at D:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.parsers.auto (D:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request.mixin._encode (D:\NB\node_modules\restler\lib\restler.js:195:29)
    at D:\NB\node_modules\restler\lib\restler.js:154:16
    at Request.mixin._decode (D:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (D:\NB\node_modules\restler\lib\restler.js:147:14)
[2018-08-14 16:57:57.835] [ERROR] dateFileLog - { [Error: HA_ERR_AUTOINC_ERANGE: Out of range value for column 'UserOID' at row 1]
  code: 'HA_ERR_AUTOINC_ERANGE',
  errno: 167,
  sqlState: '22003',
  index: 0 }
Error: HA_ERR_AUTOINC_ERANGE: Out of range value for column 'UserOID' at row 1
    at Query.Sequence._packetToError (D:\NB\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\NB\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\NB\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\NB\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    --------------------
    at Protocol._enqueue (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\NB\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:128:25)
    at getConnection.success (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:119:13)
    at Object.exports.safeSuccess (D:\NB\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.handleResult (D:\NB\yujiang.Foil.Node\src\yjError.js:154:12)
    at D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:57:11
    at Ping.onPing (D:\NB\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:287:14)
    at Ping.runBound [as _callback] (domain.js:300:12)
[2018-08-14 16:57:57.839] [ERROR] dateFileLog - { [Error: ER_DUP_ENTRY: Duplicate entry '0-190' for key 'PRIMARY'] code: 'ER_DUP_ENTRY', errno: 1062, sqlState: '23000', index: 0 }
Error: ER_DUP_ENTRY: Duplicate entry '0-190' for key 'PRIMARY'
    at Query.Sequence._packetToError (D:\NB\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\NB\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\NB\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\NB\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    --------------------
    at Protocol._enqueue (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\NB\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:128:25)
    at getConnection.success (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:119:13)
    at Object.exports.safeSuccess (D:\NB\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.handleResult (D:\NB\yujiang.Foil.Node\src\yjError.js:154:12)
    at D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:57:11
    at Ping.onPing (D:\NB\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:287:14)
    at Ping.runBound [as _callback] (domain.js:300:12)
[2018-08-14 16:57:57.843] [ERROR] dateFileLog - [Error: HA_ERR_AUTOINC_ERANGE: Out of range value for column 'UserOID' at row 1]
Error: HA_ERR_AUTOINC_ERANGE: Out of range value for column 'UserOID' at row 1
    at Request.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireSuccess (D:\NB\node_modules\restler\lib\restler.js:220:12)
    at D:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.parsers.auto (D:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request.mixin._encode (D:\NB\node_modules\restler\lib\restler.js:195:29)
    at D:\NB\node_modules\restler\lib\restler.js:154:16
    at Request.mixin._decode (D:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (D:\NB\node_modules\restler\lib\restler.js:147:14)
[2018-08-14 17:01:04.508] [ERROR] dateFileLog - { [Error: ER_DUP_ENTRY: Duplicate entry '0-190' for key 'PRIMARY'] code: 'ER_DUP_ENTRY', errno: 1062, sqlState: '23000', index: 0 }
Error: ER_DUP_ENTRY: Duplicate entry '0-190' for key 'PRIMARY'
    at Query.Sequence._packetToError (D:\NB\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\NB\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\NB\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\NB\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    --------------------
    at Protocol._enqueue (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\NB\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:128:25)
    at getConnection.success (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:119:13)
    at Object.exports.safeSuccess (D:\NB\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.handleResult (D:\NB\yujiang.Foil.Node\src\yjError.js:154:12)
    at D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:57:11
    at Ping.onPing (D:\NB\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:287:14)
    at Ping.runBound [as _callback] (domain.js:300:12)
[2018-08-14 17:01:04.510] [ERROR] dateFileLog - { [Error: HA_ERR_AUTOINC_ERANGE: Out of range value for column 'UserOID' at row 1]
  code: 'HA_ERR_AUTOINC_ERANGE',
  errno: 167,
  sqlState: '22003',
  index: 0 }
Error: HA_ERR_AUTOINC_ERANGE: Out of range value for column 'UserOID' at row 1
    at Query.Sequence._packetToError (D:\NB\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\NB\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\NB\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\NB\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    --------------------
    at Protocol._enqueue (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\NB\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:128:25)
    at getConnection.success (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:119:13)
    at Object.exports.safeSuccess (D:\NB\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.handleResult (D:\NB\yujiang.Foil.Node\src\yjError.js:154:12)
    at D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:57:11
    at Ping.onPing (D:\NB\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:287:14)
    at Ping.runBound [as _callback] (domain.js:300:12)
[2018-08-14 17:01:04.512] [ERROR] dateFileLog - [Error: ER_DUP_ENTRY: Duplicate entry '0-190' for key 'PRIMARY']
Error: ER_DUP_ENTRY: Duplicate entry '0-190' for key 'PRIMARY'
    at Request.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireSuccess (D:\NB\node_modules\restler\lib\restler.js:220:12)
    at D:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.parsers.auto (D:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request.mixin._encode (D:\NB\node_modules\restler\lib\restler.js:195:29)
    at D:\NB\node_modules\restler\lib\restler.js:154:16
    at Request.mixin._decode (D:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (D:\NB\node_modules\restler\lib\restler.js:147:14)
[2018-08-14 17:02:28.770] [ERROR] dateFileLog - { [Error: HA_ERR_AUTOINC_ERANGE: Out of range value for column 'UserOID' at row 1]
  code: 'HA_ERR_AUTOINC_ERANGE',
  errno: 167,
  sqlState: '22003',
  index: 0 }
Error: HA_ERR_AUTOINC_ERANGE: Out of range value for column 'UserOID' at row 1
    at Query.Sequence._packetToError (D:\NB\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\NB\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\NB\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\NB\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    --------------------
    at Protocol._enqueue (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\NB\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:128:25)
    at getConnection.success (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:119:13)
    at Object.exports.safeSuccess (D:\NB\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.handleResult (D:\NB\yujiang.Foil.Node\src\yjError.js:154:12)
    at D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:57:11
    at Ping.onPing (D:\NB\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:287:14)
    at Ping.runBound [as _callback] (domain.js:300:12)
[2018-08-14 17:02:28.773] [ERROR] dateFileLog - { [Error: ER_DUP_ENTRY: Duplicate entry '0-190' for key 'PRIMARY'] code: 'ER_DUP_ENTRY', errno: 1062, sqlState: '23000', index: 0 }
Error: ER_DUP_ENTRY: Duplicate entry '0-190' for key 'PRIMARY'
    at Query.Sequence._packetToError (D:\NB\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\NB\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\NB\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\NB\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    --------------------
    at Protocol._enqueue (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\NB\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:128:25)
    at getConnection.success (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:119:13)
    at Object.exports.safeSuccess (D:\NB\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.handleResult (D:\NB\yujiang.Foil.Node\src\yjError.js:154:12)
    at D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:57:11
    at Ping.onPing (D:\NB\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:287:14)
    at Ping.runBound [as _callback] (domain.js:300:12)
[2018-08-14 17:02:28.775] [ERROR] dateFileLog - [Error: HA_ERR_AUTOINC_ERANGE: Out of range value for column 'UserOID' at row 1]
Error: HA_ERR_AUTOINC_ERANGE: Out of range value for column 'UserOID' at row 1
    at Request.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireSuccess (D:\NB\node_modules\restler\lib\restler.js:220:12)
    at D:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.parsers.auto (D:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request.mixin._encode (D:\NB\node_modules\restler\lib\restler.js:195:29)
    at D:\NB\node_modules\restler\lib\restler.js:154:16
    at Request.mixin._decode (D:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (D:\NB\node_modules\restler\lib\restler.js:147:14)
[2018-08-14 17:03:49.065] [ERROR] dateFileLog - [Error: ReferenceError: now is not defined<br> &nbsp; &nbsp;at module.exports (D:\NB\tm.FGEMS\bizServer\biz\MSInfo\addUsers.{post}.{m}.js:14:17)<br> &nbsp; &nbsp;at buildData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:256:6)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:198:5<br> &nbsp; &nbsp;at Object.module.exports.read (D:\NB\yujiang.Foil.Node\src\yjMVC.cache.js:80:4)<br> &nbsp; &nbsp;at loadData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:192:15)<br> &nbsp; &nbsp;at rrnmv (D:\NB\yujiang.Foil.Node\src\yjMVC.js:188:3)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:290:4<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (D:\NB\node_modules\express\lib\router\layer.js:95:5)<br> &nbsp; &nbsp;at next (D:\NB\node_modules\express\lib\router\route.js:131:13)<br> &nbsp; &nbsp;at Route.dispatch (D:\NB\node_modules\express\lib\router\route.js:112:3)
]
Error: ReferenceError: now is not defined<br> &nbsp; &nbsp;at module.exports (D:\NB\tm.FGEMS\bizServer\biz\MSInfo\addUsers.{post}.{m}.js:14:17)<br> &nbsp; &nbsp;at buildData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:256:6)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:198:5<br> &nbsp; &nbsp;at Object.module.exports.read (D:\NB\yujiang.Foil.Node\src\yjMVC.cache.js:80:4)<br> &nbsp; &nbsp;at loadData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:192:15)<br> &nbsp; &nbsp;at rrnmv (D:\NB\yujiang.Foil.Node\src\yjMVC.js:188:3)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:290:4<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (D:\NB\node_modules\express\lib\router\layer.js:95:5)<br> &nbsp; &nbsp;at next (D:\NB\node_modules\express\lib\router\route.js:131:13)<br> &nbsp; &nbsp;at Route.dispatch (D:\NB\node_modules\express\lib\router\route.js:112:3)

    at Request.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireSuccess (D:\NB\node_modules\restler\lib\restler.js:220:12)
    at D:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.parsers.auto (D:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request.mixin._encode (D:\NB\node_modules\restler\lib\restler.js:195:29)
    at D:\NB\node_modules\restler\lib\restler.js:154:16
    at Request.mixin._decode (D:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (D:\NB\node_modules\restler\lib\restler.js:147:14)
[2018-08-14 17:04:33.921] [ERROR] dateFileLog - [Error: ReferenceError: Now is not defined<br> &nbsp; &nbsp;at module.exports (D:\NB\tm.FGEMS\bizServer\biz\MSInfo\addUsers.{post}.{m}.js:14:17)<br> &nbsp; &nbsp;at buildData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:256:6)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:198:5<br> &nbsp; &nbsp;at Object.module.exports.read (D:\NB\yujiang.Foil.Node\src\yjMVC.cache.js:80:4)<br> &nbsp; &nbsp;at loadData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:192:15)<br> &nbsp; &nbsp;at rrnmv (D:\NB\yujiang.Foil.Node\src\yjMVC.js:188:3)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:290:4<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (D:\NB\node_modules\express\lib\router\layer.js:95:5)<br> &nbsp; &nbsp;at next (D:\NB\node_modules\express\lib\router\route.js:131:13)<br> &nbsp; &nbsp;at Route.dispatch (D:\NB\node_modules\express\lib\router\route.js:112:3)
]
Error: ReferenceError: Now is not defined<br> &nbsp; &nbsp;at module.exports (D:\NB\tm.FGEMS\bizServer\biz\MSInfo\addUsers.{post}.{m}.js:14:17)<br> &nbsp; &nbsp;at buildData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:256:6)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:198:5<br> &nbsp; &nbsp;at Object.module.exports.read (D:\NB\yujiang.Foil.Node\src\yjMVC.cache.js:80:4)<br> &nbsp; &nbsp;at loadData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:192:15)<br> &nbsp; &nbsp;at rrnmv (D:\NB\yujiang.Foil.Node\src\yjMVC.js:188:3)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:290:4<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (D:\NB\node_modules\express\lib\router\layer.js:95:5)<br> &nbsp; &nbsp;at next (D:\NB\node_modules\express\lib\router\route.js:131:13)<br> &nbsp; &nbsp;at Route.dispatch (D:\NB\node_modules\express\lib\router\route.js:112:3)

    at Request.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireSuccess (D:\NB\node_modules\restler\lib\restler.js:220:12)
    at D:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.parsers.auto (D:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request.mixin._encode (D:\NB\node_modules\restler\lib\restler.js:195:29)
    at D:\NB\node_modules\restler\lib\restler.js:154:16
    at Request.mixin._decode (D:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (D:\NB\node_modules\restler\lib\restler.js:147:14)
[2018-08-14 17:07:08.300] [ERROR] dateFileLog - { [Error: ER_DUP_ENTRY: Duplicate entry '2147483647-190' for key 'PRIMARY'] code: 'ER_DUP_ENTRY', errno: 1062, sqlState: '23000', index: 0 }
Error: ER_DUP_ENTRY: Duplicate entry '2147483647-190' for key 'PRIMARY'
    at Query.Sequence._packetToError (D:\NB\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\NB\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\NB\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\NB\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    --------------------
    at Protocol._enqueue (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\NB\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:128:25)
    at getConnection.success (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:119:13)
    at Object.exports.safeSuccess (D:\NB\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.handleResult (D:\NB\yujiang.Foil.Node\src\yjError.js:154:12)
    at D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:57:11
    at Ping.onPing (D:\NB\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:287:14)
    at Ping.runBound [as _callback] (domain.js:300:12)
[2018-08-14 17:07:08.303] [ERROR] dateFileLog - { [Error: ER_DUP_ENTRY: Duplicate entry '2147483647' for key 'PRIMARY'] code: 'ER_DUP_ENTRY', errno: 1062, sqlState: '23000', index: 0 }
Error: ER_DUP_ENTRY: Duplicate entry '2147483647' for key 'PRIMARY'
    at Query.Sequence._packetToError (D:\NB\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\NB\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\NB\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\NB\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    --------------------
    at Protocol._enqueue (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\NB\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:128:25)
    at getConnection.success (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:119:13)
    at Object.exports.safeSuccess (D:\NB\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.handleResult (D:\NB\yujiang.Foil.Node\src\yjError.js:154:12)
    at D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:57:11
    at Ping.onPing (D:\NB\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:287:14)
    at Ping.runBound [as _callback] (domain.js:300:12)
[2018-08-14 17:07:08.304] [ERROR] dateFileLog - [Error: ER_DUP_ENTRY: Duplicate entry '2147483647-190' for key 'PRIMARY']
Error: ER_DUP_ENTRY: Duplicate entry '2147483647-190' for key 'PRIMARY'
    at Request.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireSuccess (D:\NB\node_modules\restler\lib\restler.js:220:12)
    at D:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.parsers.auto (D:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request.mixin._encode (D:\NB\node_modules\restler\lib\restler.js:195:29)
    at D:\NB\node_modules\restler\lib\restler.js:154:16
    at Request.mixin._decode (D:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (D:\NB\node_modules\restler\lib\restler.js:147:14)
[2018-08-14 17:08:28.924] [ERROR] dateFileLog - [Error: Can't set headers after they are sent.]
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:344:11)
    at ServerResponse.header (D:\NB\node_modules\express\lib\response.js:718:10)
    at ServerResponse.send (D:\NB\node_modules\express\lib\response.js:163:12)
    at ServerResponse.json (D:\NB\node_modules\express\lib\response.js:249:15)
    at ServerResponse.send (D:\NB\node_modules\express\lib\response.js:151:21)
    at proc_success (D:\NB\yujiang.Foil.Node\src\yjMVC.js:111:13)
    at Object.sender.success (D:\NB\yujiang.Foil.Node\src\yjMVC.js:239:8)
    at yjDBService.exec.success (D:\NB\tm.FGEMS\bizServer\biz\MSInfo\addUsers.{post}.{m}.js:62:17)
    at Object.exports.safeSuccess (D:\NB\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.handleResult (D:\NB\yujiang.Foil.Node\src\yjError.js:154:12)
[2018-08-14 17:11:19.838] [ERROR] dateFileLog - { [Error: ER_DUP_ENTRY: Duplicate entry '2147483647' for key 'PRIMARY'] code: 'ER_DUP_ENTRY', errno: 1062, sqlState: '23000', index: 0 }
Error: ER_DUP_ENTRY: Duplicate entry '2147483647' for key 'PRIMARY'
    at Query.Sequence._packetToError (D:\NB\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\NB\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\NB\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\NB\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    --------------------
    at Protocol._enqueue (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\NB\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:128:25)
    at getConnection.success (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:119:13)
    at Object.exports.safeSuccess (D:\NB\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.handleResult (D:\NB\yujiang.Foil.Node\src\yjError.js:154:12)
    at D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:57:11
    at Ping.onPing (D:\NB\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:287:14)
    at Ping.runBound [as _callback] (domain.js:300:12)
[2018-08-14 17:11:19.841] [ERROR] dateFileLog - { [Error: ER_DUP_ENTRY: Duplicate entry '2147483647-190' for key 'PRIMARY'] code: 'ER_DUP_ENTRY', errno: 1062, sqlState: '23000', index: 0 }
Error: ER_DUP_ENTRY: Duplicate entry '2147483647-190' for key 'PRIMARY'
    at Query.Sequence._packetToError (D:\NB\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\NB\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\NB\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\NB\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    --------------------
    at Protocol._enqueue (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\NB\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:128:25)
    at getConnection.success (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:119:13)
    at Object.exports.safeSuccess (D:\NB\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.handleResult (D:\NB\yujiang.Foil.Node\src\yjError.js:154:12)
    at D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:57:11
    at Ping.onPing (D:\NB\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:287:14)
    at Ping.runBound [as _callback] (domain.js:300:12)
[2018-08-14 17:11:19.845] [ERROR] dateFileLog - [Error: ER_DUP_ENTRY: Duplicate entry '2147483647' for key 'PRIMARY']
Error: ER_DUP_ENTRY: Duplicate entry '2147483647' for key 'PRIMARY'
    at Request.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireSuccess (D:\NB\node_modules\restler\lib\restler.js:220:12)
    at D:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.parsers.auto (D:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request.mixin._encode (D:\NB\node_modules\restler\lib\restler.js:195:29)
    at D:\NB\node_modules\restler\lib\restler.js:154:16
    at Request.mixin._decode (D:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (D:\NB\node_modules\restler\lib\restler.js:147:14)
[2018-08-14 17:14:51.629] [ERROR] dateFileLog - [Error: ReferenceError: DateTime is not defined<br> &nbsp; &nbsp;at genID (D:\NB\tm.FGEMS\bizServer\biz\MSInfo\addUsers.{post}.{m}.js:21:13)<br> &nbsp; &nbsp;at module.exports (D:\NB\tm.FGEMS\bizServer\biz\MSInfo\addUsers.{post}.{m}.js:27:18)<br> &nbsp; &nbsp;at buildData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:256:6)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:198:5<br> &nbsp; &nbsp;at Object.module.exports.read (D:\NB\yujiang.Foil.Node\src\yjMVC.cache.js:80:4)<br> &nbsp; &nbsp;at loadData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:192:15)<br> &nbsp; &nbsp;at rrnmv (D:\NB\yujiang.Foil.Node\src\yjMVC.js:188:3)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:290:4<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (D:\NB\node_modules\express\lib\router\layer.js:95:5)<br> &nbsp; &nbsp;at next (D:\NB\node_modules\express\lib\router\route.js:131:13)
]
Error: ReferenceError: DateTime is not defined<br> &nbsp; &nbsp;at genID (D:\NB\tm.FGEMS\bizServer\biz\MSInfo\addUsers.{post}.{m}.js:21:13)<br> &nbsp; &nbsp;at module.exports (D:\NB\tm.FGEMS\bizServer\biz\MSInfo\addUsers.{post}.{m}.js:27:18)<br> &nbsp; &nbsp;at buildData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:256:6)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:198:5<br> &nbsp; &nbsp;at Object.module.exports.read (D:\NB\yujiang.Foil.Node\src\yjMVC.cache.js:80:4)<br> &nbsp; &nbsp;at loadData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:192:15)<br> &nbsp; &nbsp;at rrnmv (D:\NB\yujiang.Foil.Node\src\yjMVC.js:188:3)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:290:4<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (D:\NB\node_modules\express\lib\router\layer.js:95:5)<br> &nbsp; &nbsp;at next (D:\NB\node_modules\express\lib\router\route.js:131:13)

    at Request.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireSuccess (D:\NB\node_modules\restler\lib\restler.js:220:12)
    at D:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.parsers.auto (D:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request.mixin._encode (D:\NB\node_modules\restler\lib\restler.js:195:29)
    at D:\NB\node_modules\restler\lib\restler.js:154:16
    at Request.mixin._decode (D:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (D:\NB\node_modules\restler\lib\restler.js:147:14)
[2018-08-14 17:15:32.161] [ERROR] dateFileLog - [Error: TypeError: Cannot read property &#39;ToString&#39; of undefined<br> &nbsp; &nbsp;at genID (D:\NB\tm.FGEMS\bizServer\biz\MSInfo\addUsers.{post}.{m}.js:21:21)<br> &nbsp; &nbsp;at module.exports (D:\NB\tm.FGEMS\bizServer\biz\MSInfo\addUsers.{post}.{m}.js:27:18)<br> &nbsp; &nbsp;at buildData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:256:6)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:198:5<br> &nbsp; &nbsp;at Object.module.exports.read (D:\NB\yujiang.Foil.Node\src\yjMVC.cache.js:80:4)<br> &nbsp; &nbsp;at loadData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:192:15)<br> &nbsp; &nbsp;at rrnmv (D:\NB\yujiang.Foil.Node\src\yjMVC.js:188:3)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:290:4<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (D:\NB\node_modules\express\lib\router\layer.js:95:5)<br> &nbsp; &nbsp;at next (D:\NB\node_modules\express\lib\router\route.js:131:13)
]
Error: TypeError: Cannot read property &#39;ToString&#39; of undefined<br> &nbsp; &nbsp;at genID (D:\NB\tm.FGEMS\bizServer\biz\MSInfo\addUsers.{post}.{m}.js:21:21)<br> &nbsp; &nbsp;at module.exports (D:\NB\tm.FGEMS\bizServer\biz\MSInfo\addUsers.{post}.{m}.js:27:18)<br> &nbsp; &nbsp;at buildData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:256:6)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:198:5<br> &nbsp; &nbsp;at Object.module.exports.read (D:\NB\yujiang.Foil.Node\src\yjMVC.cache.js:80:4)<br> &nbsp; &nbsp;at loadData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:192:15)<br> &nbsp; &nbsp;at rrnmv (D:\NB\yujiang.Foil.Node\src\yjMVC.js:188:3)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:290:4<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (D:\NB\node_modules\express\lib\router\layer.js:95:5)<br> &nbsp; &nbsp;at next (D:\NB\node_modules\express\lib\router\route.js:131:13)

    at Request.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireSuccess (D:\NB\node_modules\restler\lib\restler.js:220:12)
    at D:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.parsers.auto (D:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request.mixin._encode (D:\NB\node_modules\restler\lib\restler.js:195:29)
    at D:\NB\node_modules\restler\lib\restler.js:154:16
    at Request.mixin._decode (D:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (D:\NB\node_modules\restler\lib\restler.js:147:14)
[2018-08-14 17:42:35.294] [ERROR] dateFileLog - { [Error: ER_DUP_ENTRY: Duplicate entry '2147483647' for key 'PRIMARY'] code: 'ER_DUP_ENTRY', errno: 1062, sqlState: '23000', index: 0 }
Error: ER_DUP_ENTRY: Duplicate entry '2147483647' for key 'PRIMARY'
    at Query.Sequence._packetToError (D:\NB\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\NB\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\NB\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\NB\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    --------------------
    at Protocol._enqueue (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\NB\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:128:25)
    at getConnection.success (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:119:13)
    at Object.exports.safeSuccess (D:\NB\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.handleResult (D:\NB\yujiang.Foil.Node\src\yjError.js:154:12)
    at D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:57:11
    at Ping.onPing (D:\NB\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:287:14)
    at Ping.runBound [as _callback] (domain.js:300:12)
[2018-08-14 17:42:35.297] [ERROR] dateFileLog - { [Error: ER_DUP_ENTRY: Duplicate entry '2147483647-190' for key 'PRIMARY'] code: 'ER_DUP_ENTRY', errno: 1062, sqlState: '23000', index: 0 }
Error: ER_DUP_ENTRY: Duplicate entry '2147483647-190' for key 'PRIMARY'
    at Query.Sequence._packetToError (D:\NB\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\NB\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\NB\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\NB\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    --------------------
    at Protocol._enqueue (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\NB\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:128:25)
    at getConnection.success (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:119:13)
    at Object.exports.safeSuccess (D:\NB\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.handleResult (D:\NB\yujiang.Foil.Node\src\yjError.js:154:12)
    at D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:57:11
    at Ping.onPing (D:\NB\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:287:14)
    at Ping.runBound [as _callback] (domain.js:300:12)
[2018-08-14 17:42:35.300] [ERROR] dateFileLog - [Error: ER_DUP_ENTRY: Duplicate entry '2147483647' for key 'PRIMARY']
Error: ER_DUP_ENTRY: Duplicate entry '2147483647' for key 'PRIMARY'
    at Request.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireSuccess (D:\NB\node_modules\restler\lib\restler.js:220:12)
    at D:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.parsers.auto (D:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request.mixin._encode (D:\NB\node_modules\restler\lib\restler.js:195:29)
    at D:\NB\node_modules\restler\lib\restler.js:154:16
    at Request.mixin._decode (D:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (D:\NB\node_modules\restler\lib\restler.js:147:14)
[2018-08-14 17:44:24.548] [ERROR] dateFileLog - { [Error: ER_DUP_ENTRY: Duplicate entry '0EC001' for key 'UserAID'] code: 'ER_DUP_ENTRY', errno: 1062, sqlState: '23000', index: 0 }
Error: ER_DUP_ENTRY: Duplicate entry '0EC001' for key 'UserAID'
    at Query.Sequence._packetToError (D:\NB\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\NB\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\NB\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\NB\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    --------------------
    at Protocol._enqueue (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\NB\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:128:25)
    at getConnection.success (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:119:13)
    at Object.exports.safeSuccess (D:\NB\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.handleResult (D:\NB\yujiang.Foil.Node\src\yjError.js:154:12)
    at D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:57:11
    at Ping.onPing (D:\NB\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:287:14)
    at Ping.runBound [as _callback] (domain.js:300:12)
[2018-08-14 17:44:24.550] [ERROR] dateFileLog - [Error: ER_DUP_ENTRY: Duplicate entry '0EC001' for key 'UserAID']
Error: ER_DUP_ENTRY: Duplicate entry '0EC001' for key 'UserAID'
    at Request.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireSuccess (D:\NB\node_modules\restler\lib\restler.js:220:12)
    at D:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.parsers.auto (D:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request.mixin._encode (D:\NB\node_modules\restler\lib\restler.js:195:29)
    at D:\NB\node_modules\restler\lib\restler.js:154:16
    at Request.mixin._decode (D:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (D:\NB\node_modules\restler\lib\restler.js:147:14)
[2018-08-14 17:44:24.567] [ERROR] dateFileLog - [Error: Can't set headers after they are sent.]
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:344:11)
    at ServerResponse.header (D:\NB\node_modules\express\lib\response.js:718:10)
    at ServerResponse.send (D:\NB\node_modules\express\lib\response.js:163:12)
    at ServerResponse.json (D:\NB\node_modules\express\lib\response.js:249:15)
    at ServerResponse.send (D:\NB\node_modules\express\lib\response.js:151:21)
    at proc_success (D:\NB\yujiang.Foil.Node\src\yjMVC.js:111:13)
    at Object.sender.success (D:\NB\yujiang.Foil.Node\src\yjMVC.js:239:8)
    at yjDBService.exec.success (D:\NB\tm.FGEMS\bizServer\biz\MSInfo\addUsers.{post}.{m}.js:80:17)
    at Object.exports.safeSuccess (D:\NB\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.handleResult (D:\NB\yujiang.Foil.Node\src\yjError.js:154:12)
[2018-08-14 17:44:53.308] [ERROR] dateFileLog - { [Error: ER_DUP_ENTRY: Duplicate entry '2147483647-190' for key 'PRIMARY'] code: 'ER_DUP_ENTRY', errno: 1062, sqlState: '23000', index: 0 }
Error: ER_DUP_ENTRY: Duplicate entry '2147483647-190' for key 'PRIMARY'
    at Query.Sequence._packetToError (D:\NB\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\NB\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\NB\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\NB\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    --------------------
    at Protocol._enqueue (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\NB\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:128:25)
    at getConnection.success (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:119:13)
    at Object.exports.safeSuccess (D:\NB\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.handleResult (D:\NB\yujiang.Foil.Node\src\yjError.js:154:12)
    at D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:57:11
    at Ping.onPing (D:\NB\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:287:14)
    at Ping.runBound [as _callback] (domain.js:300:12)
[2018-08-14 17:44:53.310] [ERROR] dateFileLog - [Error: ER_DUP_ENTRY: Duplicate entry '2147483647-190' for key 'PRIMARY']
Error: ER_DUP_ENTRY: Duplicate entry '2147483647-190' for key 'PRIMARY'
    at Request.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireSuccess (D:\NB\node_modules\restler\lib\restler.js:220:12)
    at D:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.parsers.auto (D:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request.mixin._encode (D:\NB\node_modules\restler\lib\restler.js:195:29)
    at D:\NB\node_modules\restler\lib\restler.js:154:16
    at Request.mixin._decode (D:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (D:\NB\node_modules\restler\lib\restler.js:147:14)
[2018-08-14 17:44:53.320] [ERROR] dateFileLog - [Error: Can't set headers after they are sent.]
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:344:11)
    at ServerResponse.header (D:\NB\node_modules\express\lib\response.js:718:10)
    at ServerResponse.send (D:\NB\node_modules\express\lib\response.js:163:12)
    at ServerResponse.json (D:\NB\node_modules\express\lib\response.js:249:15)
    at ServerResponse.send (D:\NB\node_modules\express\lib\response.js:151:21)
    at proc_success (D:\NB\yujiang.Foil.Node\src\yjMVC.js:111:13)
    at Object.sender.success (D:\NB\yujiang.Foil.Node\src\yjMVC.js:239:8)
    at yjDBService.exec.success (D:\NB\tm.FGEMS\bizServer\biz\MSInfo\addUsers.{post}.{m}.js:62:17)
    at Object.exports.safeSuccess (D:\NB\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.handleResult (D:\NB\yujiang.Foil.Node\src\yjError.js:154:12)
[2018-08-14 17:46:51.472] [ERROR] dateFileLog - [Error: Can't set headers after they are sent.]
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:344:11)
    at ServerResponse.header (D:\NB\node_modules\express\lib\response.js:718:10)
    at ServerResponse.send (D:\NB\node_modules\express\lib\response.js:163:12)
    at ServerResponse.json (D:\NB\node_modules\express\lib\response.js:249:15)
    at ServerResponse.send (D:\NB\node_modules\express\lib\response.js:151:21)
    at proc_success (D:\NB\yujiang.Foil.Node\src\yjMVC.js:111:13)
    at Object.sender.success (D:\NB\yujiang.Foil.Node\src\yjMVC.js:239:8)
    at yjDBService.exec.success (D:\NB\tm.FGEMS\bizServer\biz\MSInfo\addUsers.{post}.{m}.js:80:17)
    at Object.exports.safeSuccess (D:\NB\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.handleResult (D:\NB\yujiang.Foil.Node\src\yjError.js:154:12)
[2018-08-14 18:05:57.755] [ERROR] dateFileLog - { [Error: HA_ERR_AUTOINC_ERANGE: Out of range value for column 'UserOID' at row 1]
  code: 'HA_ERR_AUTOINC_ERANGE',
  errno: 167,
  sqlState: '22003',
  index: 0 }
Error: HA_ERR_AUTOINC_ERANGE: Out of range value for column 'UserOID' at row 1
    at Query.Sequence._packetToError (D:\NB\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\NB\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\NB\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\NB\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    --------------------
    at Protocol._enqueue (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\NB\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:128:25)
    at getConnection.success (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:119:13)
    at Object.exports.safeSuccess (D:\NB\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.handleResult (D:\NB\yujiang.Foil.Node\src\yjError.js:154:12)
    at D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:57:11
    at Ping.onPing (D:\NB\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:287:14)
    at Ping.runBound [as _callback] (domain.js:300:12)
[2018-08-14 18:05:57.758] [ERROR] dateFileLog - [Error: HA_ERR_AUTOINC_ERANGE: Out of range value for column 'UserOID' at row 1]
Error: HA_ERR_AUTOINC_ERANGE: Out of range value for column 'UserOID' at row 1
    at Request.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireSuccess (D:\NB\node_modules\restler\lib\restler.js:220:12)
    at D:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.parsers.auto (D:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request.mixin._encode (D:\NB\node_modules\restler\lib\restler.js:195:29)
    at D:\NB\node_modules\restler\lib\restler.js:154:16
    at Request.mixin._decode (D:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (D:\NB\node_modules\restler\lib\restler.js:147:14)
[2018-08-14 18:07:40.323] [ERROR] dateFileLog - { [Error: HA_ERR_AUTOINC_ERANGE: Out of range value for column 'UserOID' at row 1]
  code: 'HA_ERR_AUTOINC_ERANGE',
  errno: 167,
  sqlState: '22003',
  index: 0 }
Error: HA_ERR_AUTOINC_ERANGE: Out of range value for column 'UserOID' at row 1
    at Query.Sequence._packetToError (D:\NB\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\NB\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\NB\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\NB\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    --------------------
    at Protocol._enqueue (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\NB\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:128:25)
    at getConnection.success (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:119:13)
    at Object.exports.safeSuccess (D:\NB\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.handleResult (D:\NB\yujiang.Foil.Node\src\yjError.js:154:12)
    at D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:57:11
    at Ping.onPing (D:\NB\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:287:14)
    at Ping.runBound [as _callback] (domain.js:300:12)
[2018-08-14 18:07:40.325] [ERROR] dateFileLog - [Error: HA_ERR_AUTOINC_ERANGE: Out of range value for column 'UserOID' at row 1]
Error: HA_ERR_AUTOINC_ERANGE: Out of range value for column 'UserOID' at row 1
    at Request.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireSuccess (D:\NB\node_modules\restler\lib\restler.js:220:12)
    at D:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.parsers.auto (D:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request.mixin._encode (D:\NB\node_modules\restler\lib\restler.js:195:29)
    at D:\NB\node_modules\restler\lib\restler.js:154:16
    at Request.mixin._decode (D:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (D:\NB\node_modules\restler\lib\restler.js:147:14)
[2018-08-14 18:08:27.615] [ERROR] dateFileLog - { [Error: HA_ERR_AUTOINC_ERANGE: Out of range value for column 'UserOID' at row 1]
  code: 'HA_ERR_AUTOINC_ERANGE',
  errno: 167,
  sqlState: '22003',
  index: 0 }
Error: HA_ERR_AUTOINC_ERANGE: Out of range value for column 'UserOID' at row 1
    at Query.Sequence._packetToError (D:\NB\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\NB\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\NB\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\NB\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    --------------------
    at Protocol._enqueue (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\NB\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:128:25)
    at getConnection.success (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:119:13)
    at Object.exports.safeSuccess (D:\NB\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.handleResult (D:\NB\yujiang.Foil.Node\src\yjError.js:154:12)
    at D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:57:11
    at Ping.onPing (D:\NB\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:287:14)
    at Ping.runBound [as _callback] (domain.js:300:12)
[2018-08-14 18:08:27.617] [ERROR] dateFileLog - [Error: HA_ERR_AUTOINC_ERANGE: Out of range value for column 'UserOID' at row 1]
Error: HA_ERR_AUTOINC_ERANGE: Out of range value for column 'UserOID' at row 1
    at Request.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireSuccess (D:\NB\node_modules\restler\lib\restler.js:220:12)
    at D:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.parsers.auto (D:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request.mixin._encode (D:\NB\node_modules\restler\lib\restler.js:195:29)
    at D:\NB\node_modules\restler\lib\restler.js:154:16
    at Request.mixin._decode (D:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (D:\NB\node_modules\restler\lib\restler.js:147:14)
[2018-08-14 18:09:08.535] [ERROR] dateFileLog - { [Error: HA_ERR_AUTOINC_ERANGE: Out of range value for column 'UserOID' at row 1]
  code: 'HA_ERR_AUTOINC_ERANGE',
  errno: 167,
  sqlState: '22003',
  index: 0 }
Error: HA_ERR_AUTOINC_ERANGE: Out of range value for column 'UserOID' at row 1
    at Query.Sequence._packetToError (D:\NB\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\NB\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\NB\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\NB\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    --------------------
    at Protocol._enqueue (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\NB\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:128:25)
    at getConnection.success (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:119:13)
    at Object.exports.safeSuccess (D:\NB\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.handleResult (D:\NB\yujiang.Foil.Node\src\yjError.js:154:12)
    at D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:57:11
    at Ping.onPing (D:\NB\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:287:14)
    at Ping.runBound [as _callback] (domain.js:300:12)
[2018-08-14 18:09:08.538] [ERROR] dateFileLog - [Error: HA_ERR_AUTOINC_ERANGE: Out of range value for column 'UserOID' at row 1]
Error: HA_ERR_AUTOINC_ERANGE: Out of range value for column 'UserOID' at row 1
    at Request.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireSuccess (D:\NB\node_modules\restler\lib\restler.js:220:12)
    at D:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.parsers.auto (D:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request.mixin._encode (D:\NB\node_modules\restler\lib\restler.js:195:29)
    at D:\NB\node_modules\restler\lib\restler.js:154:16
    at Request.mixin._decode (D:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (D:\NB\node_modules\restler\lib\restler.js:147:14)
[2018-08-14 18:10:15.120] [ERROR] dateFileLog - { [Error: HA_ERR_AUTOINC_ERANGE: Out of range value for column 'UserOID' at row 1]
  code: 'HA_ERR_AUTOINC_ERANGE',
  errno: 167,
  sqlState: '22003',
  index: 0 }
Error: HA_ERR_AUTOINC_ERANGE: Out of range value for column 'UserOID' at row 1
    at Query.Sequence._packetToError (D:\NB\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\NB\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\NB\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\NB\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    --------------------
    at Protocol._enqueue (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\NB\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:128:25)
    at getConnection.success (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:119:13)
    at Object.exports.safeSuccess (D:\NB\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.handleResult (D:\NB\yujiang.Foil.Node\src\yjError.js:154:12)
    at D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:57:11
    at Ping.onPing (D:\NB\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:287:14)
    at Ping.runBound [as _callback] (domain.js:300:12)
[2018-08-14 18:10:15.123] [ERROR] dateFileLog - [Error: HA_ERR_AUTOINC_ERANGE: Out of range value for column 'UserOID' at row 1]
Error: HA_ERR_AUTOINC_ERANGE: Out of range value for column 'UserOID' at row 1
    at Request.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireSuccess (D:\NB\node_modules\restler\lib\restler.js:220:12)
    at D:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.parsers.auto (D:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request.mixin._encode (D:\NB\node_modules\restler\lib\restler.js:195:29)
    at D:\NB\node_modules\restler\lib\restler.js:154:16
    at Request.mixin._decode (D:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (D:\NB\node_modules\restler\lib\restler.js:147:14)
[2018-08-14 18:12:00.718] [ERROR] dateFileLog - [Error: 'config.security.isOpenRegister' is false. Not open to register new account.]
Error: 'config.security.isOpenRegister' is false. Not open to register new account.
    at module.exports (D:\NB\yujiang.Foil.Node.WebServer\app\account\showRegisterAccount.{m}.js:7:16)
    at buildData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:256:6)
    at D:\NB\yujiang.Foil.Node\src\yjMVC.js:198:5
    at Object.module.exports.read (D:\NB\yujiang.Foil.Node\src\yjMVC.cache.js:80:4)
    at loadData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:192:15)
    at rrnmv (D:\NB\yujiang.Foil.Node\src\yjMVC.js:188:3)
    at D:\NB\yujiang.Foil.Node\src\yjMVC.js:290:4
    at Layer.handle [as handle_request] (D:\NB\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\NB\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (D:\NB\node_modules\express\lib\router\route.js:112:3)
[2018-08-14 18:12:30.998] [ERROR] dateFileLog - [Error: Can't set headers after they are sent.]
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:344:11)
    at ServerResponse.header (D:\NB\node_modules\express\lib\response.js:718:10)
    at ServerResponse.send (D:\NB\node_modules\express\lib\response.js:163:12)
    at ServerResponse.json (D:\NB\node_modules\express\lib\response.js:249:15)
    at ServerResponse.send (D:\NB\node_modules\express\lib\response.js:151:21)
    at proc_success (D:\NB\yujiang.Foil.Node\src\yjMVC.js:111:13)
    at Object.sender.success (D:\NB\yujiang.Foil.Node\src\yjMVC.js:239:8)
    at yjDBService.exec.success (D:\NB\tm.FGEMS\bizServer\biz\MSInfo\addUsers.{post}.{m}.js:80:17)
    at Object.exports.safeSuccess (D:\NB\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.handleResult (D:\NB\yujiang.Foil.Node\src\yjError.js:154:12)
[2018-08-14 18:28:14.210] [ERROR] dateFileLog - { [Error: ER_DUP_ENTRY: Duplicate entry '0EC001' for key 'UserAID'] code: 'ER_DUP_ENTRY', errno: 1062, sqlState: '23000', index: 0 }
Error: ER_DUP_ENTRY: Duplicate entry '0EC001' for key 'UserAID'
    at Query.Sequence._packetToError (D:\NB\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\NB\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\NB\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\NB\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:536:20)
    --------------------
    at Protocol._enqueue (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\NB\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:128:25)
    at getConnection.success (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:119:13)
    at Object.exports.safeSuccess (D:\NB\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.handleResult (D:\NB\yujiang.Foil.Node\src\yjError.js:154:12)
    at D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:57:11
    at Ping.onPing (D:\NB\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:287:14)
    at Ping.runBound [as _callback] (domain.js:300:12)
[2018-08-14 18:28:14.214] [ERROR] dateFileLog - [Error: ER_DUP_ENTRY: Duplicate entry '0EC001' for key 'UserAID']
Error: ER_DUP_ENTRY: Duplicate entry '0EC001' for key 'UserAID'
    at Request.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireSuccess (D:\NB\node_modules\restler\lib\restler.js:220:12)
    at D:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.parsers.auto (D:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request.mixin._encode (D:\NB\node_modules\restler\lib\restler.js:195:29)
    at D:\NB\node_modules\restler\lib\restler.js:154:16
    at Request.mixin._decode (D:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (D:\NB\node_modules\restler\lib\restler.js:147:14)
[2018-08-14 18:28:31.082] [ERROR] dateFileLog - { [Error: ER_DUP_ENTRY: Duplicate entry '0EJ001' for key 'UserAID'] code: 'ER_DUP_ENTRY', errno: 1062, sqlState: '23000', index: 0 }
Error: ER_DUP_ENTRY: Duplicate entry '0EJ001' for key 'UserAID'
    at Query.Sequence._packetToError (D:\NB\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\NB\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\NB\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\NB\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:536:20)
    --------------------
    at Protocol._enqueue (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\NB\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:128:25)
    at getConnection.success (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:119:13)
    at Object.exports.safeSuccess (D:\NB\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.handleResult (D:\NB\yujiang.Foil.Node\src\yjError.js:154:12)
    at D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:57:11
    at Ping.onPing (D:\NB\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:287:14)
    at Ping.runBound [as _callback] (domain.js:300:12)
[2018-08-14 18:28:31.084] [ERROR] dateFileLog - [Error: ER_DUP_ENTRY: Duplicate entry '0EJ001' for key 'UserAID']
Error: ER_DUP_ENTRY: Duplicate entry '0EJ001' for key 'UserAID'
    at Request.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireSuccess (D:\NB\node_modules\restler\lib\restler.js:220:12)
    at D:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.parsers.auto (D:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request.mixin._encode (D:\NB\node_modules\restler\lib\restler.js:195:29)
    at D:\NB\node_modules\restler\lib\restler.js:154:16
    at Request.mixin._decode (D:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (D:\NB\node_modules\restler\lib\restler.js:147:14)
