[2018-08-15 08:54:22.148] [ERROR] dateFileLog - [Error: ReferenceError: sql is not defined<br> &nbsp; &nbsp;at module.exports (D:\NB\tm.FGEMS\bizServer\biz\MSInfo\authUsers.{post}.{m}.js:15:15)<br> &nbsp; &nbsp;at buildData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:256:6)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:198:5<br> &nbsp; &nbsp;at Object.module.exports.read (D:\NB\yujiang.Foil.Node\src\yjMVC.cache.js:80:4)<br> &nbsp; &nbsp;at loadData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:192:15)<br> &nbsp; &nbsp;at rrnmv (D:\NB\yujiang.Foil.Node\src\yjMVC.js:188:3)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:290:4<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (D:\NB\node_modules\express\lib\router\layer.js:95:5)<br> &nbsp; &nbsp;at next (D:\NB\node_modules\express\lib\router\route.js:131:13)<br> &nbsp; &nbsp;at Route.dispatch (D:\NB\node_modules\express\lib\router\route.js:112:3)
]
Error: ReferenceError: sql is not defined<br> &nbsp; &nbsp;at module.exports (D:\NB\tm.FGEMS\bizServer\biz\MSInfo\authUsers.{post}.{m}.js:15:15)<br> &nbsp; &nbsp;at buildData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:256:6)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:198:5<br> &nbsp; &nbsp;at Object.module.exports.read (D:\NB\yujiang.Foil.Node\src\yjMVC.cache.js:80:4)<br> &nbsp; &nbsp;at loadData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:192:15)<br> &nbsp; &nbsp;at rrnmv (D:\NB\yujiang.Foil.Node\src\yjMVC.js:188:3)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:290:4<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (D:\NB\node_modules\express\lib\router\layer.js:95:5)<br> &nbsp; &nbsp;at next (D:\NB\node_modules\express\lib\router\route.js:131:13)<br> &nbsp; &nbsp;at Route.dispatch (D:\NB\node_modules\express\lib\router\route.js:112:3)

    at Request.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireSuccess (D:\NB\node_modules\restler\lib\restler.js:220:12)
    at D:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.parsers.auto (D:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request.mixin._encode (D:\NB\node_modules\restler\lib\restler.js:195:29)
    at D:\NB\node_modules\restler\lib\restler.js:154:16
    at Request.mixin._decode (D:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (D:\NB\node_modules\restler\lib\restler.js:147:14)
[2018-08-15 08:54:51.195] [ERROR] dateFileLog - [ReferenceError: result is not defined]
ReferenceError: result is not defined
    at yjDBService.exec.success (D:\NB\tm.FGEMS\bizServer\biz\MSInfo\authUsers.{post}.{m}.js:20:43)
    at Object.exports.safeSuccess (D:\NB\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.handleResult (D:\NB\yujiang.Foil.Node\src\yjError.js:154:12)
    at Query.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:202:38)
    at bound (domain.js:287:14)
    at Query.runBound [as _callback] (domain.js:300:12)
    at Query.Sequence.end (D:\NB\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
    at Query._handleFinalResultPacket (D:\NB\node_modules\mysql\lib\protocol\sequences\Query.js:143:8)
    at Query.EofPacket (D:\NB\node_modules\mysql\lib\protocol\sequences\Query.js:127:8)
    at Protocol._parsePacket (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:271:23)
[2018-08-15 08:54:51.201] [ERROR] dateFileLog - [Error: result is not defined]
Error: result is not defined
    at Request.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireSuccess (D:\NB\node_modules\restler\lib\restler.js:220:12)
    at D:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.parsers.auto (D:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request.mixin._encode (D:\NB\node_modules\restler\lib\restler.js:195:29)
    at D:\NB\node_modules\restler\lib\restler.js:154:16
    at Request.mixin._decode (D:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (D:\NB\node_modules\restler\lib\restler.js:147:14)
[2018-08-15 08:54:51.240] [ERROR] dateFileLog - [Error: Can't set headers after they are sent.]
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:344:11)
    at ServerResponse.header (D:\NB\node_modules\express\lib\response.js:718:10)
    at ServerResponse.send (D:\NB\node_modules\express\lib\response.js:163:12)
    at ServerResponse.json (D:\NB\node_modules\express\lib\response.js:249:15)
    at ServerResponse.send (D:\NB\node_modules\express\lib\response.js:151:21)
    at proc_success (D:\NB\yujiang.Foil.Node\src\yjMVC.js:111:13)
    at Object.sender.success (D:\NB\yujiang.Foil.Node\src\yjMVC.js:239:8)
    at yjDBService.exec.success (D:\NB\tm.FGEMS\bizServer\biz\MSInfo\authUsers.{post}.{m}.js:38:16)
    at Object.exports.safeSuccess (D:\NB\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.handleResult (D:\NB\yujiang.Foil.Node\src\yjError.js:154:12)
[2018-08-15 09:00:15.040] [ERROR] dateFileLog - [Error: ReferenceError: onsole is not defined<br> &nbsp; &nbsp;at module.exports (D:\NB\tm.FGEMS\bizServer\biz\MSInfo\authUsers.{post}.{m}.js:27:5)<br> &nbsp; &nbsp;at buildData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:256:6)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:198:5<br> &nbsp; &nbsp;at Object.module.exports.read (D:\NB\yujiang.Foil.Node\src\yjMVC.cache.js:80:4)<br> &nbsp; &nbsp;at loadData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:192:15)<br> &nbsp; &nbsp;at rrnmv (D:\NB\yujiang.Foil.Node\src\yjMVC.js:188:3)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:290:4<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (D:\NB\node_modules\express\lib\router\layer.js:95:5)<br> &nbsp; &nbsp;at next (D:\NB\node_modules\express\lib\router\route.js:131:13)<br> &nbsp; &nbsp;at Route.dispatch (D:\NB\node_modules\express\lib\router\route.js:112:3)
]
Error: ReferenceError: onsole is not defined<br> &nbsp; &nbsp;at module.exports (D:\NB\tm.FGEMS\bizServer\biz\MSInfo\authUsers.{post}.{m}.js:27:5)<br> &nbsp; &nbsp;at buildData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:256:6)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:198:5<br> &nbsp; &nbsp;at Object.module.exports.read (D:\NB\yujiang.Foil.Node\src\yjMVC.cache.js:80:4)<br> &nbsp; &nbsp;at loadData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:192:15)<br> &nbsp; &nbsp;at rrnmv (D:\NB\yujiang.Foil.Node\src\yjMVC.js:188:3)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:290:4<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (D:\NB\node_modules\express\lib\router\layer.js:95:5)<br> &nbsp; &nbsp;at next (D:\NB\node_modules\express\lib\router\route.js:131:13)<br> &nbsp; &nbsp;at Route.dispatch (D:\NB\node_modules\express\lib\router\route.js:112:3)

    at Request.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireSuccess (D:\NB\node_modules\restler\lib\restler.js:220:12)
    at D:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.parsers.auto (D:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request.mixin._encode (D:\NB\node_modules\restler\lib\restler.js:195:29)
    at D:\NB\node_modules\restler\lib\restler.js:154:16
    at Request.mixin._decode (D:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (D:\NB\node_modules\restler\lib\restler.js:147:14)
[2018-08-15 09:09:32.947] [ERROR] dateFileLog - 已经授权,无需再次授权
[2018-08-15 09:09:32.956] [ERROR] dateFileLog - [Error]
Error
    at Request.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireSuccess (D:\NB\node_modules\restler\lib\restler.js:220:12)
    at D:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.parsers.auto (D:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request.mixin._encode (D:\NB\node_modules\restler\lib\restler.js:195:29)
    at D:\NB\node_modules\restler\lib\restler.js:154:16
    at Request.mixin._decode (D:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (D:\NB\node_modules\restler\lib\restler.js:147:14)
[2018-08-15 09:09:33.000] [ERROR] dateFileLog - [Error: Can't set headers after they are sent.]
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:344:11)
    at ServerResponse.header (D:\NB\node_modules\express\lib\response.js:718:10)
    at ServerResponse.json (D:\NB\node_modules\express\lib\response.js:246:10)
    at ServerResponse.send (D:\NB\node_modules\express\lib\response.js:151:21)
    at proc_success (D:\NB\yujiang.Foil.Node\src\yjMVC.js:111:13)
    at Object.sender.success (D:\NB\yujiang.Foil.Node\src\yjMVC.js:239:8)
    at yjDBService.exec.success (D:\NB\tm.FGEMS\bizServer\biz\MSInfo\authUsers.{post}.{m}.js:56:16)
    at Object.exports.safeSuccess (D:\NB\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.handleResult (D:\NB\yujiang.Foil.Node\src\yjError.js:154:12)
    at Query.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:202:38)
[2018-08-15 09:10:26.460] [ERROR] dateFileLog - 已经授权,无需再次授权
[2018-08-15 09:10:26.464] [ERROR] dateFileLog - [Error]
Error
    at Request.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireSuccess (D:\NB\node_modules\restler\lib\restler.js:220:12)
    at D:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.parsers.auto (D:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request.mixin._encode (D:\NB\node_modules\restler\lib\restler.js:195:29)
    at D:\NB\node_modules\restler\lib\restler.js:154:16
    at Request.mixin._decode (D:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (D:\NB\node_modules\restler\lib\restler.js:147:14)
[2018-08-15 09:11:36.901] [ERROR] dateFileLog - 已经授权,无需再次授权
[2018-08-15 09:11:36.912] [ERROR] dateFileLog - [Error]
Error
    at Request.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireSuccess (D:\NB\node_modules\restler\lib\restler.js:220:12)
    at D:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.parsers.auto (D:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request.mixin._encode (D:\NB\node_modules\restler\lib\restler.js:195:29)
    at D:\NB\node_modules\restler\lib\restler.js:154:16
    at Request.mixin._decode (D:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (D:\NB\node_modules\restler\lib\restler.js:147:14)
[2018-08-15 09:54:33.188] [ERROR] dateFileLog - [Error: Can't set headers after they are sent.]
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:344:11)
    at ServerResponse.header (D:\NB\node_modules\express\lib\response.js:718:10)
    at ServerResponse.send (D:\NB\node_modules\express\lib\response.js:163:12)
    at proc_success (D:\NB\yujiang.Foil.Node\src\yjMVC.js:111:13)
    at Object.sender.success (D:\NB\yujiang.Foil.Node\src\yjMVC.js:239:8)
    at yjDBService.exec.success (D:\NB\tm.FGEMS\bizServer\biz\MSInfo\authUsers.{post}.{m}.js:69:16)
    at Object.exports.safeSuccess (D:\NB\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.handleResult (D:\NB\yujiang.Foil.Node\src\yjError.js:154:12)
    at Query.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:202:38)
    at bound (domain.js:287:14)
[2018-08-15 09:57:19.391] [ERROR] dateFileLog - [Error: Password is not correct.]
Error: Password is not correct.
    at callback_getUser (D:\NB\yujiang.Foil.Node.BizServer\biz\account\checkLogin.js:148:17)
    at D:\NB\yujiang.Foil.Node\src\yjError.js:134:4
    at Object.exports.safeSuccess (D:\NB\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.safeCallback (D:\NB\yujiang.Foil.Node\src\yjError.js:133:11)
    at Object.exports.handleResult (D:\NB\yujiang.Foil.Node\src\yjError.js:148:11)
    at Query.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:202:38)
    at bound (domain.js:287:14)
    at Query.runBound [as _callback] (domain.js:300:12)
    at Query.Sequence.end (D:\NB\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
    at Query._handleFinalResultPacket (D:\NB\node_modules\mysql\lib\protocol\sequences\Query.js:143:8)
[2018-08-15 09:57:19.394] [ERROR] dateFileLog - [Error: 密码不对。]
Error: 密码不对。
    at Request.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireSuccess (D:\NB\node_modules\restler\lib\restler.js:220:12)
    at D:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.parsers.auto (D:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request.mixin._encode (D:\NB\node_modules\restler\lib\restler.js:195:29)
    at D:\NB\node_modules\restler\lib\restler.js:154:16
    at Request.mixin._decode (D:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (D:\NB\node_modules\restler\lib\restler.js:147:14)
[2018-08-15 09:57:42.648] [ERROR] dateFileLog - { [Error: ER_DUP_ENTRY: Duplicate entry '0CS001' for key 'UserAID'] code: 'ER_DUP_ENTRY', errno: 1062, sqlState: '23000', index: 0 }
Error: ER_DUP_ENTRY: Duplicate entry '0CS001' for key 'UserAID'
    at Query.Sequence._packetToError (D:\NB\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\NB\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\NB\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\NB\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:536:20)
    --------------------
    at Protocol._enqueue (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\NB\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:128:25)
    at getConnection.success (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:119:13)
    at Object.exports.safeSuccess (D:\NB\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.handleResult (D:\NB\yujiang.Foil.Node\src\yjError.js:154:12)
    at D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:57:11
    at Ping.onPing (D:\NB\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:287:14)
    at Ping.runBound [as _callback] (domain.js:300:12)
[2018-08-15 09:57:42.651] [ERROR] dateFileLog - [Error: ER_DUP_ENTRY: Duplicate entry '0CS001' for key 'UserAID']
Error: ER_DUP_ENTRY: Duplicate entry '0CS001' for key 'UserAID'
    at Request.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireSuccess (D:\NB\node_modules\restler\lib\restler.js:220:12)
    at D:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.parsers.auto (D:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request.mixin._encode (D:\NB\node_modules\restler\lib\restler.js:195:29)
    at D:\NB\node_modules\restler\lib\restler.js:154:16
    at Request.mixin._decode (D:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (D:\NB\node_modules\restler\lib\restler.js:147:14)
[2018-08-15 09:58:31.238] [ERROR] dateFileLog - { [Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '?,230,0,1)' at line 1]
  code: 'ER_PARSE_ERROR',
  errno: 1064,
  sqlState: '42000',
  index: 0 }
Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '?,230,0,1)' at line 1
    at Query.Sequence._packetToError (D:\NB\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\NB\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\NB\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\NB\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:536:20)
    --------------------
    at Protocol._enqueue (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\NB\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:128:25)
    at getConnection.success (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:119:13)
    at Object.exports.safeSuccess (D:\NB\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.handleResult (D:\NB\yujiang.Foil.Node\src\yjError.js:154:12)
    at D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:57:11
    at Ping.onPing (D:\NB\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:287:14)
    at Ping.runBound [as _callback] (domain.js:300:12)
[2018-08-15 09:58:31.243] [ERROR] dateFileLog - [Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '?,230,0,1)' at line 1]
Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '?,230,0,1)' at line 1
    at Request.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireSuccess (D:\NB\node_modules\restler\lib\restler.js:220:12)
    at D:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.parsers.auto (D:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request.mixin._encode (D:\NB\node_modules\restler\lib\restler.js:195:29)
    at D:\NB\node_modules\restler\lib\restler.js:154:16
    at Request.mixin._decode (D:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (D:\NB\node_modules\restler\lib\restler.js:147:14)
[2018-08-15 09:58:31.269] [ERROR] dateFileLog - [Error: Can't set headers after they are sent.]
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:344:11)
    at ServerResponse.header (D:\NB\node_modules\express\lib\response.js:718:10)
    at ServerResponse.send (D:\NB\node_modules\express\lib\response.js:163:12)
    at proc_success (D:\NB\yujiang.Foil.Node\src\yjMVC.js:111:13)
    at Object.sender.success (D:\NB\yujiang.Foil.Node\src\yjMVC.js:239:8)
    at yjDBService.exec.success (D:\NB\tm.FGEMS\bizServer\biz\MSInfo\authUsers.{post}.{m}.js:57:16)
    at Object.exports.safeSuccess (D:\NB\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.handleResult (D:\NB\yujiang.Foil.Node\src\yjError.js:154:12)
    at Query.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:202:38)
    at bound (domain.js:287:14)
